package disasm

import (
	"strconv"
	"strings"
)

// DetectSharedStubCall recognizes Dart AOT's compiler-synthesized "shared
// stub" idiom on ARM64: a small Code object with NO owning Function (its
// Code.OwnerRef doesn't resolve to any NamedObject at all -- confirmed via a
// real sample: 85 out of ~7986 isolate Code objects in one real
// compare_sample build), generated by the precompiler to share a common
// "save every live register, call one THR-cached runtime entry point,
// restore, return" sequence across many call sites that happen to need the
// exact same live-register shape (e.g. the stack-overflow-check slow path).
// These have no Dart-source name to recover -- ARCHITECTURE.md's "Discarded
// Code function naming" section covers the SEPARATE, name-recoverable case
// (a real Function whose Code was discarded but whose code_index scalar
// still exists); this is a genuinely different category with no Function at
// all behind it.
//
// Verified on a real sample (disassembly of Code refID 26430,
// OwnerRef=1/no NamedObject): a full callee-saved-register push via the
// Dart stack pointer register (X15/SPREG), `LDR X30,[X26,#520]` (THR+0x208 =
// CallToRuntime in that sample's verified ThreadStubOffsets table), `BLR
// X30`, register restore, `RET`. The exact save/restore SHAPE varies (at
// least 4 different prologue variants were found in one real sample, not
// just the register-push-everything one above), but the owner-unresolvable
// signal plus the THR-cached-offset call pattern are consistent across all
// of them -- so this function does NOT try to match a specific prologue
// shape, only the underlying THR-relative "ldr Xn,[X26,#off]; ...; blr Xn"
// call pattern (scanning the WHOLE function, not just its start), exactly
// mirroring internal/decompiler/lift.go's per-instruction THR-stub-offset
// check.
//
// Callers are expected to gate this on "Code.OwnerRef has no resolvable
// NamedObject" themselves (see cmd/aotopsy/decompile_native_cmd.go) --
// this function has no way to check that itself and will happily match
// inside a REAL function's body too (every real function legitimately
// calls WriteBarrier/AllocateObject/etc. the same way), which would produce
// a wrong name if applied unconditionally.
//
// x86_64 is NOT covered: whether Dart AOT's x86_64 backend generates an
// analogous shared-stub shape was not verified against a real sample, and
// this project's "don't guess wrong" rule means it stays unhandled (falls
// back to the pre-existing stub_<hex>/sub_<hex> display) rather than
// assuming x86_64 works the same way.
func DetectSharedStubCall(insts []Inst, threadStubOffsets map[int64]string) (string, bool) {
	if len(threadStubOffsets) == 0 {
		return "", false
	}
	for i, in := range insts {
		fields := strings.Fields(in.Text)
		if len(fields) < 2 || strings.ToLower(fields[0]) != "ldr" {
			continue
		}
		rest := strings.TrimSpace(strings.TrimPrefix(in.Text, fields[0]))
		parts := strings.SplitN(rest, ",", 2)
		if len(parts) != 2 {
			continue
		}
		dstReg := strings.ToLower(strings.TrimSpace(parts[0]))
		mem := strings.ToLower(strings.TrimSpace(parts[1]))
		if !strings.HasPrefix(mem, "[x26,") {
			continue
		}
		off, ok := parseARM64MemOffset(mem)
		if !ok {
			continue
		}
		name, ok := threadStubOffsets[off]
		if !ok {
			continue
		}
		for j := i + 1; j < len(insts) && j < i+6; j++ {
			f2 := strings.Fields(insts[j].Text)
			if len(f2) < 2 || strings.ToLower(f2[0]) != "blr" {
				continue
			}
			if strings.ToLower(strings.TrimSuffix(f2[1], ",")) == dstReg {
				return name, true
			}
		}
	}
	return "", false
}

// parseARM64MemOffset parses the "#<off>]" tail of a lowercased ARM64
// memory operand like "[x26,#520]" (arm64asm renders these in decimal, no
// "0x" prefix, confirmed on real disassembly output -- unlike x86asm's
// Mem.String(), which does use hex).
func parseARM64MemOffset(mem string) (int64, bool) {
	idx := strings.Index(mem, "#")
	if idx < 0 {
		return 0, false
	}
	s := strings.TrimSuffix(strings.TrimSpace(mem[idx+1:]), "]")
	v, err := strconv.ParseInt(s, 10, 64)
	if err != nil {
		return 0, false
	}
	return v, true
}
