package disasm

// Per-Dart-version, ordered VM_STUB_CODE_LIST expansion (dart-lang/sdk's
// runtime/vm/stub_code_list.h), used to name the VM isolate's stub Code
// objects by position -- see ARCHITECTURE.md's "Stub naming" section for
// the full derivation and verification. Index i in this slice is stub
// entry i (StubCode::k<Name>Index), in the EXACT order StubCode::Init()
// generates them, which matches the Code cluster's own sequential index
// order in the VM-isolate snapshot region (empirically verified against
// two real compiled samples: index 0 is always a ~12-byte function,
// consistent with the trivially-small GetCStackPointer).
//
// Deliberately does NOT cover every stub: real samples show 9 MORE Code
// objects in the VM-isolate snapshot than this list has entries (169 vs
// 160 for Dart 3.7.0, 171 vs 162 for Dart 3.9.2 -- the same +9 on both),
// almost certainly VM_TYPE_TESTING_STUB_CODE_LIST's 9 entries
// (DefaultTypeTest, TopTypeTypeTest, etc., generated by a separate
// TypeTestingStubGenerator subsystem, not StubCode::Init()'s main loop).
// Their exact position wasn't pinned down with full confidence, so they
// are deliberately left unnamed rather than guessed -- see
// BuildVMStubNames's caller for how the boundary is enforced.
var (
	stubNames370 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocationProbePoint", "AllocateArray",
		"AllocateMint", "AllocateDouble", "AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
		"AllocateInt8Array", "AllocateUint8Array", "AllocateUint8ClampedArray", "AllocateInt16Array",
		"AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array", "AllocateInt64Array",
		"AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs",
		"AllocateMintSharedWithoutFPURegs", "AllocateClosure", "AllocateClosureGeneric",
		"AllocateClosureTA", "AllocateClosureTAGeneric", "AllocateContext", "AllocateGrowableArray",
		"AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow", "AllocateRecord",
		"AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named",
		"AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2", "CloneContext",
		"CallToRuntime", "LazyCompile", "InterpretCall", "ResumeInterpreter", "CallBootstrapNative",
		"CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction",
		"OptimizeFunction", "InvokeDartCode", "InvokeDartCodeFromBytecode", "DebugStepCheck",
		"SwitchableCallMiss", "MonomorphicSmiableCheck", "SingleTargetCall", "ICCallThroughCode",
		"MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget",
		"Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow",
		"UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint",
		"UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint", "OneArgCheckInlineCache",
		"TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache",
		"OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache",
		"ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "NullIsAssignableToType",
		"Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache",
		"Subtype6TestCache", "Subtype7TestCache", "CallClosureNoSuchMethod",
		"FrameAwaitingMaterialization", "AsynchronousGapMarker", "NotLoaded", "DispatchTableNullError",
		"LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs",
		"NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs",
		"RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs",
		"StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck",
		"EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
		"CallNativeThroughSafepoint", "FfiCallbackTrampoline", "InitStaticField", "InitLateStaticField",
		"InitLateFinalStaticField", "InitInstanceField", "InitLateInstanceField",
		"InitLateFinalInstanceField", "InitSharedLateStaticField", "InitSharedLateFinalStaticField",
		"Throw", "ReThrow", "InstanceOf", "InstantiateType",
		"InstantiateTypeNonNullableClassTypeParameter", "InstantiateTypeNullableClassTypeParameter",
		"InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter",
		"InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await",
		"AwaitWithTypeCheck", "InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture",
		"InitAsyncStar", "YieldAsyncStar", "ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart",
		"SuspendSyncStarAtYield", "AsyncExceptionHandler", "CloneSuspendState", "FfiAsyncCallbackSend",
		"UnknownDartCode",
	} // count: 160

	// stubNames2120 verified against dart-lang/sdk runtime/vm/stub_code_list.h
	// at tag 2.12.0, and it follows the SAME convention as every other table
	// here: VM_TYPE_TESTING_STUB_CODE_LIST's 9 entries are EXCLUDED, because
	// composeVMStubEmissionOrder (stuborder.go) inserts them after the
	// Subtype7TestCache anchor.
	//
	// An earlier revision of this table included them inline, on the theory
	// that 2.12.0 differs from 3.x by embedding the type-testing list "in the
	// middle" rather than at the end. That premise is wrong: measured against
	// the SDK, VM_TYPE_TESTING_STUB_CODE_LIST(V) sits between
	// Subtype7TestCache and CallClosureNoSuchMethod in 2.12.0, 3.12.2 and
	// 3.13.0 alike -- the same position in all three. Including it here made
	// composeVMStubEmissionOrder insert the 9 names a SECOND time, yielding a
	// 125-entry composed list with 9 duplicates against a VM snapshot that has
	// exactly 116 Code objects, so every name from Subtype7TestCache onward
	// was shifted by 9.
	stubNames2120 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateContext",
		"AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow", "AllocateUnhandledException", "CloneContext",
		"CallToRuntime", "LazyCompile", "CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative",
		"FixCallersTarget", "CallStaticFunction", "OptimizeFunction", "InvokeDartCode", "DebugStepCheck",
		"SwitchableCallMiss", "MonomorphicSmiableCheck", "SingleTargetCall", "ICCallThroughCode", "MegamorphicCall",
		"FixAllocationStubTarget", "Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck",
		"OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint", "OneArgCheckInlineCache",
		"TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache",
		"TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall", "AssertSubtype",
		"TypeIsTopTypeForSubtyping", "TypeIsTopTypeForSubtypingNullSafe", "NullIsAssignableToType", "NullIsAssignableToTypeNullSafe", "Subtype1TestCache",
		"Subtype3TestCache", "Subtype5TestCache", "Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization",
		"AsynchronousGapMarker", "NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs", "NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs",
		"NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint", "ExitSafepoint", "CallNativeThroughSafepoint",
		"InitStaticField", "InitInstanceField", "InitLateInstanceField", "InitLateFinalInstanceField", "Throw",
		"ReThrow", "AssertBoolean", "InstanceOf", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher",
	} // count: 107 (+9 TTS inserted by composeVMStubEmissionOrder = 116)

	// stubNames2176/305/325/343/362 verified against the real
	// dart-lang/sdk runtime/vm/stub_code_list.h at the 2.17.6, 3.0.5,
	// 3.2.5, 3.4.3, and 3.6.2 tags respectively (same extraction method
	// as 370/392 above: VM_STUB_CODE_LIST(V) expansion in macro order,
	// excluding the separately-generated VM_TYPE_TESTING_STUB_CODE_LIST's
	// 9 entries -- the deliberate +9 unnamed tail documented above).
	// Coverage: stubNames325 also serves 3.1.0 and 3.3.0 (same
	// stub_code_list.h within that compatibility window); stubNames343
	// also serves 3.5.0. Note 3.6.2 differs from 3.7.0 by exactly one
	// entry: 3.7.0 inserts AllocationProbePoint at index 7 (after
	// ArrayWriteBarrier), so 3.6.2 cannot reuse stubNames370.
	stubNames2176 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow",
		"AllocateUnhandledException", "BoxDouble", "CloneContext", "CallToRuntime", "LazyCompile",
		"CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction",
		"OptimizeFunction", "InvokeDartCode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget", "Deoptimize",
		"DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint",
		"UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint", "OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache",
		"SmiLessInlineCache", "SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall",
		"OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall", "AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping",
		"TypeIsTopTypeForSubtypingNullSafe", "NullIsAssignableToType", "NullIsAssignableToTypeNullSafe", "Subtype1TestCache", "Subtype3TestCache",
		"Subtype5TestCache", "Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker",
		"NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs", "NullErrorSharedWithFPURegs",
		"NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs", "NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs",
		"RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
		"CallNativeThroughSafepoint", "InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "Throw", "ReThrow", "AssertBoolean",
		"InstanceOf", "InstantiateType", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA", "InstantiateTypeArgumentsMayShareFunctionTA",
		"NoSuchMethodDispatcher", "UnknownDartCode",
	} // count: 122

	// stubNames2190 is Dart 2.19.0's VM_STUB_CODE_LIST (151 entries, the 9
	// type-testing stubs excluded per this file's convention).
	//
	// Added when a real 2.19.0 sample first existed. Until then VMStubNames
	// had no case for it, so every VM stub call in a 2.19.0 binary went
	// unnamed: the sample reported 0 stub resolutions against 29-35 on its
	// siblings built from the same Dart source.
	stubNames2190 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow",
		"AllocateRecord", "AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named",
		"AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2", "CloneContext",
		"CallToRuntime", "LazyCompile", "CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative",
		"FixCallersTarget", "CallStaticFunction", "OptimizeFunction", "InvokeDartCode", "DebugStepCheck",
		"SwitchableCallMiss", "MonomorphicSmiableCheck", "SingleTargetCall", "ICCallThroughCode", "MegamorphicCall",
		"FixAllocationStubTarget", "FixParameterizedAllocationStubTarget", "Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow",
		"UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache",
		"OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "TypeIsTopTypeForSubtypingNullSafe", "NullIsAssignableToType",
		"NullIsAssignableToTypeNullSafe", "Subtype1TestCache", "Subtype3TestCache", "Subtype5TestCache", "Subtype7TestCache",
		"CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker", "NotLoaded", "DispatchTableNullError",
		"LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs", "NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs",
		"WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
		"CallNativeThroughSafepoint", "InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "Throw", "ReThrow", "AssertBoolean",
		"InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter", "InstantiateTypeNullableClassTypeParameter", "InstantiateTypeLegacyClassTypeParameter",
		"InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeLegacyFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "InitAsync", "Resume",
		"ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar", "ReturnAsyncStar",
		"InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler", "CloneSuspendState",
		"UnknownDartCode",
	}

	stubNames305 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow",
		"AllocateRecord", "AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named",
		"AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2", "CloneContext",
		"CallToRuntime", "LazyCompile", "CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative",
		"FixCallersTarget", "CallStaticFunction", "OptimizeFunction", "InvokeDartCode", "DebugStepCheck",
		"SwitchableCallMiss", "MonomorphicSmiableCheck", "SingleTargetCall", "ICCallThroughCode", "MegamorphicCall",
		"FixAllocationStubTarget", "FixParameterizedAllocationStubTarget", "Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow",
		"UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache",
		"OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "TypeIsTopTypeForSubtypingNullSafe", "NullIsAssignableToType",
		"NullIsAssignableToTypeNullSafe", "Subtype1TestCache", "Subtype3TestCache", "Subtype5TestCache", "Subtype7TestCache",
		"CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker", "NotLoaded", "DispatchTableNullError",
		"LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs", "NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs",
		"WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
		"CallNativeThroughSafepoint", "InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "Throw", "ReThrow", "AssertBoolean",
		"InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter", "InstantiateTypeNullableClassTypeParameter", "InstantiateTypeLegacyClassTypeParameter",
		"InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeLegacyFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck", "InitAsync",
		"Resume", "ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar",
		"ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler",
		"CloneSuspendState", "UnknownDartCode",
	} // count: 152

	stubNames325 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow",
		"AllocateRecord", "AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named",
		"AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2", "CloneContext",
		"CallToRuntime", "LazyCompile", "CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative",
		"FixCallersTarget", "CallStaticFunction", "OptimizeFunction", "InvokeDartCode", "DebugStepCheck",
		"SwitchableCallMiss", "MonomorphicSmiableCheck", "SingleTargetCall", "ICCallThroughCode", "MegamorphicCall",
		"FixAllocationStubTarget", "FixParameterizedAllocationStubTarget", "Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow",
		"UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache",
		"OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "TypeIsTopTypeForSubtypingNullSafe", "NullIsAssignableToType",
		"NullIsAssignableToTypeNullSafe", "Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache",
		"Subtype6TestCache", "Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker",
		"NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs", "NullErrorSharedWithFPURegs",
		"NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs", "NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs",
		"RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs",
		"StackOverflowSharedWithoutFPURegs", "DoubleToInteger", "OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint",
		"ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress", "CallNativeThroughSafepoint", "FfiCallbackTrampoline", "InitStaticField",
		"InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField", "InitLateInstanceField", "InitLateFinalInstanceField",
		"Throw", "ReThrow", "AssertBoolean", "InstanceOf", "InstantiateType",
		"InstantiateTypeNonNullableClassTypeParameter", "InstantiateTypeNullableClassTypeParameter", "InstantiateTypeLegacyClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter",
		"InstantiateTypeLegacyFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA", "InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher",
		"Await", "AwaitWithTypeCheck", "InitAsync", "Resume", "ReturnAsync",
		"ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar", "ReturnAsyncStar", "InitSyncStar",
		"SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler", "CloneSuspendState", "FfiAsyncCallbackSend",
		"UnknownDartCode",
	} // count: 156

	stubNames343 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateClosureGeneric", "AllocateClosureTA", "AllocateClosureTAGeneric", "AllocateContext", "AllocateGrowableArray",
		"AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow", "AllocateRecord", "AllocateRecord2",
		"AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named", "AllocateUnhandledException", "BoxDouble",
		"BoxFloat32x4", "BoxFloat64x2", "CloneContext", "CallToRuntime", "LazyCompile",
		"CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction",
		"OptimizeFunction", "InvokeDartCode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget",
		"Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck",
		"ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint", "OneArgCheckInlineCache", "TwoArgsCheckInlineCache",
		"SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache",
		"ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall", "AssertSubtype", "AssertAssignable",
		"TypeIsTopTypeForSubtyping", "TypeIsTopTypeForSubtypingNullSafe", "NullIsAssignableToType", "NullIsAssignableToTypeNullSafe", "Subtype1TestCache",
		"Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache", "Subtype6TestCache", "Subtype7TestCache",
		"CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker", "NotLoaded", "DispatchTableNullError",
		"LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs", "NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs",
		"WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
		"CallNativeThroughSafepoint", "FfiCallbackTrampoline", "InitStaticField", "InitLateStaticField", "InitLateFinalStaticField",
		"InitInstanceField", "InitLateInstanceField", "InitLateFinalInstanceField", "Throw", "ReThrow",
		"AssertBoolean", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter", "InstantiateTypeNullableClassTypeParameter",
		"InstantiateTypeLegacyClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeLegacyFunctionTypeParameter", "InstantiateTypeArguments",
		"InstantiateTypeArgumentsMayShareInstantiatorTA", "InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck",
		"InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar",
		"YieldAsyncStar", "ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield",
		"AsyncExceptionHandler", "CloneSuspendState", "FfiAsyncCallbackSend", "UnknownDartCode",
	} // count: 159

	stubNames362 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateClosureGeneric", "AllocateClosureTA", "AllocateClosureTAGeneric", "AllocateContext", "AllocateGrowableArray",
		"AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow", "AllocateRecord", "AllocateRecord2",
		"AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named", "AllocateUnhandledException", "BoxDouble",
		"BoxFloat32x4", "BoxFloat64x2", "CloneContext", "CallToRuntime", "LazyCompile",
		"InterpretCall", "ResumeInterpreter", "CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative",
		"FixCallersTarget", "CallStaticFunction", "OptimizeFunction", "InvokeDartCode", "InvokeDartCodeFromBytecode",
		"DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck", "SingleTargetCall", "ICCallThroughCode",
		"MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget", "Deoptimize", "DeoptimizeLazyFromReturn",
		"DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint",
		"RuntimeCallBreakpoint", "OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache",
		"SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall",
		"TwoArgsUnoptimizedStaticCall", "AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "NullIsAssignableToType",
		"Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache", "Subtype6TestCache",
		"Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker", "NotLoaded",
		"DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs", "NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs",
		"NullArgErrorSharedWithFPURegs", "NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs",
		"RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs",
		"DoubleToInteger", "OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint", "ExitSafepoint",
		"ExitSafepointIgnoreUnwindInProgress", "CallNativeThroughSafepoint", "FfiCallbackTrampoline", "InitStaticField", "InitLateStaticField",
		"InitLateFinalStaticField", "InitInstanceField", "InitLateInstanceField", "InitLateFinalInstanceField", "InitSharedLateStaticField",
		"InitSharedLateFinalStaticField", "Throw", "ReThrow", "InstanceOf", "InstantiateType",
		"InstantiateTypeNonNullableClassTypeParameter", "InstantiateTypeNullableClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeArguments",
		"InstantiateTypeArgumentsMayShareInstantiatorTA", "InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck",
		"InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar",
		"YieldAsyncStar", "ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield",
		"AsyncExceptionHandler", "CloneSuspendState", "FfiAsyncCallbackSend", "UnknownDartCode",
	} // count: 159

	stubNames392 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "RunExceptionHandlerUnbox",
		"DeoptForRewind", "WriteBarrier", "WriteBarrierWrappers", "ArrayWriteBarrier",
		"AllocationProbePoint", "AllocateArray", "AllocateMint", "AllocateDouble", "AllocateFloat32x4",
		"AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array",
		"AllocateUint32Array", "AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array",
		"AllocateFloat64Array", "AllocateFloat32x4Array", "AllocateInt32x4Array",
		"AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs",
		"AllocateClosure", "AllocateClosureGeneric", "AllocateClosureTA", "AllocateClosureTAGeneric",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized",
		"AllocateObjectSlow", "AllocateRecord", "AllocateRecord2", "AllocateRecord2Named",
		"AllocateRecord3", "AllocateRecord3Named", "AllocateUnhandledException", "BoxDouble",
		"BoxFloat32x4", "BoxFloat64x2", "CloneContext", "CallToRuntime", "LazyCompile", "InterpretCall",
		"ResumeInterpreter", "CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative",
		"FixCallersTarget", "CallStaticFunction", "OptimizeFunction", "InvokeDartCode",
		"InvokeDartCodeFromBytecode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget",
		"FixParameterizedAllocationStubTarget", "Deoptimize", "DeoptimizeLazyFromReturn",
		"DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck",
		"OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint",
		"RuntimeCallBreakpoint", "OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache",
		"SmiLessInlineCache", "SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache",
		"TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall",
		"OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall", "AssertSubtype",
		"AssertAssignable", "TypeIsTopTypeForSubtyping", "NullIsAssignableToType", "Subtype1TestCache",
		"Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache", "Subtype6TestCache",
		"Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization",
		"AsynchronousGapMarker", "NotLoaded", "DispatchTableNullError",
		"LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs",
		"NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs",
		"RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs",
		"FieldAccessErrorSharedWithFPURegs", "FieldAccessErrorSharedWithoutFPURegs",
		"StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck",
		"EnterSafepoint", "ExitSafepoint", "CallNativeThroughSafepoint", "FfiCallbackTrampoline",
		"InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "InitSharedLateStaticField", "Throw",
		"ReThrow", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter",
		"InstantiateTypeNullableClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter",
		"InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeArguments",
		"InstantiateTypeArgumentsMayShareInstantiatorTA", "InstantiateTypeArgumentsMayShareFunctionTA",
		"NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck", "InitAsync", "Resume", "ReturnAsync",
		"ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar", "ReturnAsyncStar", "InitSyncStar",
		"SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler", "CloneSuspendState",
		"FfiAsyncCallbackSend", "CheckIsolateFieldAccess", "UnknownDartCode",
	} // count: 162

	// stubNames3109/3115/3122 verified against real dart-lang/sdk source at
	// the 3.10.9/3.11.5/3.12.2 tags (same method as 370/392 above). Real,
	// version-specific diffs found relative to 3.9.2 (see ARCHITECTURE.md):
	// 3.10.9 inserts FfiCallTrampoline; 3.11.5 additionally appends
	// CheckedStoreIntoShared; 3.12.2 REMOVES GetCStackPointer as the FIRST
	// entry (shifting every later index down by one relative to all
	// earlier-verified versions) and appends EnsureDeeplyImmutable.
	stubNames3109 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "RunExceptionHandlerUnbox", "DeoptForRewind",
		"WriteBarrier", "WriteBarrierWrappers", "ArrayWriteBarrier", "AllocationProbePoint", "AllocateArray",
		"AllocateMint", "AllocateDouble", "AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
		"AllocateInt8Array", "AllocateUint8Array", "AllocateUint8ClampedArray", "AllocateInt16Array",
		"AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array", "AllocateInt64Array",
		"AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs",
		"AllocateClosure", "AllocateClosureGeneric", "AllocateClosureTA", "AllocateClosureTAGeneric",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized",
		"AllocateObjectSlow", "AllocateRecord", "AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3",
		"AllocateRecord3Named", "AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
		"CloneContext", "CallToRuntime", "LazyCompile", "InterpretCall", "ResumeInterpreter", "CallBootstrapNative",
		"CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction", "OptimizeFunction",
		"InvokeDartCode", "InvokeDartCodeFromBytecode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget",
		"Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck",
		"OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache",
		"SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache",
		"ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "NullIsAssignableToType",
		"Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache", "Subtype6TestCache",
		"Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker",
		"NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs",
		"RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs",
		"WriteErrorSharedWithoutFPURegs", "FieldAccessErrorSharedWithFPURegs", "FieldAccessErrorSharedWithoutFPURegs",
		"StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck",
		"EnterSafepoint", "ExitSafepoint", "CallNativeThroughSafepoint", "FfiCallTrampoline", "FfiCallbackTrampoline",
		"InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "InitSharedLateStaticField", "Throw",
		"ReThrow", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter",
		"InstantiateTypeNullableClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter",
		"InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck",
		"InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar",
		"ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler",
		"CloneSuspendState", "FfiAsyncCallbackSend", "CheckIsolateFieldAccess", "UnknownDartCode",
	} // count: 163

	stubNames3115 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "RunExceptionHandlerUnbox", "DeoptForRewind",
		"WriteBarrier", "WriteBarrierWrappers", "ArrayWriteBarrier", "AllocationProbePoint", "AllocateArray",
		"AllocateMint", "AllocateDouble", "AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
		"AllocateInt8Array", "AllocateUint8Array", "AllocateUint8ClampedArray", "AllocateInt16Array",
		"AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array", "AllocateInt64Array",
		"AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs",
		"AllocateClosure", "AllocateClosureGeneric", "AllocateClosureTA", "AllocateClosureTAGeneric",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized",
		"AllocateObjectSlow", "AllocateRecord", "AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3",
		"AllocateRecord3Named", "AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
		"CloneContext", "CallToRuntime", "LazyCompile", "InterpretCall", "ResumeInterpreter", "CallBootstrapNative",
		"CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction", "OptimizeFunction",
		"InvokeDartCode", "InvokeDartCodeFromBytecode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget",
		"Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck",
		"OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache",
		"SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache",
		"ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "NullIsAssignableToType",
		"Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache", "Subtype6TestCache",
		"Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker",
		"NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs",
		"RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs",
		"WriteErrorSharedWithoutFPURegs", "FieldAccessErrorSharedWithFPURegs", "FieldAccessErrorSharedWithoutFPURegs",
		"StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck",
		"EnterSafepoint", "ExitSafepoint", "CallNativeThroughSafepoint", "FfiCallTrampoline", "FfiCallbackTrampoline",
		"InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "InitSharedLateStaticField", "Throw",
		"ReThrow", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter",
		"InstantiateTypeNullableClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter",
		"InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck",
		"InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar",
		"ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler",
		"CloneSuspendState", "FfiAsyncCallbackSend", "CheckIsolateFieldAccess", "CheckedStoreIntoShared",
		"UnknownDartCode",
	} // count: 164

	// stubNames3122: note GetCStackPointer is ABSENT (removed upstream at
	// this version) -- index 0 here is JumpToFrame, unlike every
	// earlier-verified version where index 0 is GetCStackPointer.
	stubNames3122 = []string{
		"JumpToFrame", "RunExceptionHandler", "RunExceptionHandlerUnbox", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocationProbePoint", "AllocateArray", "AllocateMint",
		"AllocateDouble", "AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array",
		"AllocateUint8Array", "AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array",
		"AllocateInt32Array", "AllocateUint32Array", "AllocateInt64Array", "AllocateUint64Array",
		"AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array", "AllocateInt32x4Array",
		"AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs",
		"AllocateClosure", "AllocateClosureGeneric", "AllocateClosureTA", "AllocateClosureTAGeneric",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized",
		"AllocateObjectSlow", "AllocateRecord", "AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3",
		"AllocateRecord3Named", "AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2",
		"CloneContext", "CallToRuntime", "LazyCompile", "InterpretCall", "ResumeInterpreter", "CallBootstrapNative",
		"CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction", "OptimizeFunction",
		"InvokeDartCode", "InvokeDartCodeFromBytecode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget",
		"Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck",
		"OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache",
		"SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache",
		"ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "NullIsAssignableToType",
		"Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache", "Subtype6TestCache",
		"Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker",
		"NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs",
		"RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs",
		"WriteErrorSharedWithoutFPURegs", "FieldAccessErrorSharedWithFPURegs", "FieldAccessErrorSharedWithoutFPURegs",
		"StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck",
		"EnterSafepoint", "ExitSafepoint", "CallNativeThroughSafepoint", "FfiCallTrampoline", "FfiCallbackTrampoline",
		"InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "InitSharedLateStaticField", "Throw",
		"ReThrow", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter",
		"InstantiateTypeNullableClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter",
		"InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck",
		"InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar",
		"ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler",
		"CloneSuspendState", "FfiAsyncCallbackSend", "CheckIsolateFieldAccess", "CheckedStoreIntoShared",
		"EnsureDeeplyImmutable", "UnknownDartCode",
	} // count: 164

	// stubNames3130: verified via gh api to dart-lang/sdk stub_code_list.h
	// @3.13.0, element for element, against the macro-expanded
	// VM_STUB_CODE_LIST (PROBE_POINT_STUBS_LIST included, the 9
	// VM_TYPE_TESTING_STUB_CODE_LIST entries excluded per this file's
	// convention).
	//
	// The ONLY differences from 3.12.2 are:
	//   - AllocateClosure/Generic/TA/TAGeneric REPLACED by AllocateClosure1-4
	//   - TypeIsTopTypeForSubtyping RENAMED to IsTopType
	// The count is unchanged at 164.
	//
	// An earlier revision dropped AllocationProbePoint at index 7, on the
	// theory that 3.13.0 removed it. It did not: PROBE_POINT_STUBS_LIST is
	// still expanded between ArrayWriteBarrier and AllocateArray, and the
	// #if above its definition only sets DART_TARGET_SUPPORTS_PROBE_POINTS --
	// it does not guard the macro. Dropping it shifted the 156 names after
	// index 7 by one. (Two other bullets in that revision were also wrong:
	// InitSharedLateFinalStaticField never existed in either version, and
	// FfiCallTrampoline is present in 3.12.2 too.)
	stubNames3130 = []string{
		"JumpToFrame", "RunExceptionHandler", "RunExceptionHandlerUnbox", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocationProbePoint", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array",
		"AllocateUint32Array", "AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array",
		"AllocateFloat64Array", "AllocateFloat32x4Array", "AllocateInt32x4Array", "AllocateFloat64x2Array",
		"AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure1",
		"AllocateClosure2", "AllocateClosure3", "AllocateClosure4", "AllocateContext", "AllocateGrowableArray",
		"AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow", "AllocateRecord",
		"AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named",
		"AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2", "CloneContext",
		"CallToRuntime", "LazyCompile", "InterpretCall", "ResumeInterpreter", "CallBootstrapNative",
		"CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction", "OptimizeFunction",
		"InvokeDartCode", "InvokeDartCodeFromBytecode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget",
		"Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck",
		"OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache",
		"SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache",
		"ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "IsTopType", "NullIsAssignableToType",
		"Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache", "Subtype4TestCache", "Subtype6TestCache",
		"Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker",
		"NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs",
		"NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs",
		"RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs",
		"WriteErrorSharedWithoutFPURegs", "FieldAccessErrorSharedWithFPURegs", "FieldAccessErrorSharedWithoutFPURegs",
		"StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger",
		"OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck",
		"EnterSafepoint", "ExitSafepoint", "CallNativeThroughSafepoint", "FfiCallTrampoline", "FfiCallbackTrampoline",
		"InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField",
		"InitLateInstanceField", "InitLateFinalInstanceField", "InitSharedLateStaticField", "Throw",
		"ReThrow", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter",
		"InstantiateTypeNullableClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter",
		"InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA",
		"InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck",
		"InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar",
		"ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler",
		"CloneSuspendState", "FfiAsyncCallbackSend", "CheckIsolateFieldAccess", "CheckedStoreIntoShared",
		"EnsureDeeplyImmutable", "UnknownDartCode",
	} // count: 164

	// stubNames310 / stubNames350: 3.1.0 and 3.5.0 used to borrow their
	// neighbour's table (3.1.0 -> stubNames325, 3.5.0 -> stubNames343). Both
	// borrowings were wrong, measured against the SDK:
	//
	//	3.1.0  155 entries; 3.2.5 added Subtype3TestCache -> 156.
	//	       Borrowing 3.2.5 shifted the 67 names from index 88 on.
	//	3.5.0  157 entries; 3.4.3 has 4 stubs 3.5.0 dropped
	//	       (TypeIsTopTypeForSubtypingNullSafe, NullIsAssignableToTypeNullSafe,
	//	       InstantiateTypeLegacy{Class,Function}TypeParameter) and lacks 2
	//	       that 3.5.0 added (InitShared{,Final}LateStaticField).
	//	       Borrowing 3.4.3 shifted the 71 names from index 86 on.
	//
	// Both are now their own SDK-verified lists. This is exactly what
	// TestVMStubNamesMatchSDK exists to prevent recurring.
	stubNames310 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateContext", "AllocateGrowableArray", "AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow",
		"AllocateRecord", "AllocateRecord2", "AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named",
		"AllocateUnhandledException", "BoxDouble", "BoxFloat32x4", "BoxFloat64x2", "CloneContext",
		"CallToRuntime", "LazyCompile", "CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative",
		"FixCallersTarget", "CallStaticFunction", "OptimizeFunction", "InvokeDartCode", "DebugStepCheck",
		"SwitchableCallMiss", "MonomorphicSmiableCheck", "SingleTargetCall", "ICCallThroughCode", "MegamorphicCall",
		"FixAllocationStubTarget", "FixParameterizedAllocationStubTarget", "Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow",
		"UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck", "ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint",
		"OneArgCheckInlineCache", "TwoArgsCheckInlineCache", "SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache",
		"OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache", "ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall",
		"AssertSubtype", "AssertAssignable", "TypeIsTopTypeForSubtyping", "TypeIsTopTypeForSubtypingNullSafe", "NullIsAssignableToType",
		"NullIsAssignableToTypeNullSafe", "Subtype1TestCache", "Subtype2TestCache", "Subtype4TestCache", "Subtype6TestCache",
		"Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization", "AsynchronousGapMarker", "NotLoaded",
		"DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs", "NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs",
		"NullArgErrorSharedWithFPURegs", "NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs", "NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs",
		"RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs", "StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs",
		"DoubleToInteger", "OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck", "EnterSafepoint", "ExitSafepoint",
		"ExitSafepointIgnoreUnwindInProgress", "CallNativeThroughSafepoint", "FfiCallbackTrampoline", "InitStaticField", "InitLateStaticField",
		"InitLateFinalStaticField", "InitInstanceField", "InitLateInstanceField", "InitLateFinalInstanceField", "Throw",
		"ReThrow", "AssertBoolean", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter",
		"InstantiateTypeNullableClassTypeParameter", "InstantiateTypeLegacyClassTypeParameter", "InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeLegacyFunctionTypeParameter",
		"InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA", "InstantiateTypeArgumentsMayShareFunctionTA", "NoSuchMethodDispatcher", "Await",
		"AwaitWithTypeCheck", "InitAsync", "Resume", "ReturnAsync", "ReturnAsyncNotFuture",
		"InitAsyncStar", "YieldAsyncStar", "ReturnAsyncStar", "InitSyncStar", "SuspendSyncStarAtStart",
		"SuspendSyncStarAtYield", "AsyncExceptionHandler", "CloneSuspendState", "FfiAsyncCallbackSend", "UnknownDartCode",
	} // count: 155

	stubNames350 = []string{
		"GetCStackPointer", "JumpToFrame", "RunExceptionHandler", "DeoptForRewind", "WriteBarrier",
		"WriteBarrierWrappers", "ArrayWriteBarrier", "AllocateArray", "AllocateMint", "AllocateDouble",
		"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4", "AllocateInt8Array", "AllocateUint8Array",
		"AllocateUint8ClampedArray", "AllocateInt16Array", "AllocateUint16Array", "AllocateInt32Array", "AllocateUint32Array",
		"AllocateInt64Array", "AllocateUint64Array", "AllocateFloat32Array", "AllocateFloat64Array", "AllocateFloat32x4Array",
		"AllocateInt32x4Array", "AllocateFloat64x2Array", "AllocateMintSharedWithFPURegs", "AllocateMintSharedWithoutFPURegs", "AllocateClosure",
		"AllocateClosureGeneric", "AllocateClosureTA", "AllocateClosureTAGeneric", "AllocateContext", "AllocateGrowableArray",
		"AllocateObject", "AllocateObjectParameterized", "AllocateObjectSlow", "AllocateRecord", "AllocateRecord2",
		"AllocateRecord2Named", "AllocateRecord3", "AllocateRecord3Named", "AllocateUnhandledException", "BoxDouble",
		"BoxFloat32x4", "BoxFloat64x2", "CloneContext", "CallToRuntime", "LazyCompile",
		"CallBootstrapNative", "CallNoScopeNative", "CallAutoScopeNative", "FixCallersTarget", "CallStaticFunction",
		"OptimizeFunction", "InvokeDartCode", "DebugStepCheck", "SwitchableCallMiss", "MonomorphicSmiableCheck",
		"SingleTargetCall", "ICCallThroughCode", "MegamorphicCall", "FixAllocationStubTarget", "FixParameterizedAllocationStubTarget",
		"Deoptimize", "DeoptimizeLazyFromReturn", "DeoptimizeLazyFromThrow", "UnoptimizedIdenticalWithNumberCheck", "OptimizedIdenticalWithNumberCheck",
		"ICCallBreakpoint", "UnoptStaticCallBreakpoint", "RuntimeCallBreakpoint", "OneArgCheckInlineCache", "TwoArgsCheckInlineCache",
		"SmiAddInlineCache", "SmiLessInlineCache", "SmiEqualInlineCache", "OneArgOptimizedCheckInlineCache", "TwoArgsOptimizedCheckInlineCache",
		"ZeroArgsUnoptimizedStaticCall", "OneArgUnoptimizedStaticCall", "TwoArgsUnoptimizedStaticCall", "AssertSubtype", "AssertAssignable",
		"TypeIsTopTypeForSubtyping", "NullIsAssignableToType", "Subtype1TestCache", "Subtype2TestCache", "Subtype3TestCache",
		"Subtype4TestCache", "Subtype6TestCache", "Subtype7TestCache", "CallClosureNoSuchMethod", "FrameAwaitingMaterialization",
		"AsynchronousGapMarker", "NotLoaded", "DispatchTableNullError", "LateInitializationErrorSharedWithFPURegs", "LateInitializationErrorSharedWithoutFPURegs",
		"NullErrorSharedWithFPURegs", "NullErrorSharedWithoutFPURegs", "NullArgErrorSharedWithFPURegs", "NullArgErrorSharedWithoutFPURegs", "NullCastErrorSharedWithFPURegs",
		"NullCastErrorSharedWithoutFPURegs", "RangeErrorSharedWithFPURegs", "RangeErrorSharedWithoutFPURegs", "WriteErrorSharedWithFPURegs", "WriteErrorSharedWithoutFPURegs",
		"StackOverflowSharedWithFPURegs", "StackOverflowSharedWithoutFPURegs", "DoubleToInteger", "OneArgCheckInlineCacheWithExactnessCheck", "OneArgOptimizedCheckInlineCacheWithExactnessCheck",
		"EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress", "CallNativeThroughSafepoint", "FfiCallbackTrampoline",
		"InitStaticField", "InitLateStaticField", "InitLateFinalStaticField", "InitInstanceField", "InitLateInstanceField",
		"InitLateFinalInstanceField", "InitSharedLateStaticField", "InitSharedLateFinalStaticField", "Throw", "ReThrow",
		"AssertBoolean", "InstanceOf", "InstantiateType", "InstantiateTypeNonNullableClassTypeParameter", "InstantiateTypeNullableClassTypeParameter",
		"InstantiateTypeNonNullableFunctionTypeParameter", "InstantiateTypeNullableFunctionTypeParameter", "InstantiateTypeArguments", "InstantiateTypeArgumentsMayShareInstantiatorTA", "InstantiateTypeArgumentsMayShareFunctionTA",
		"NoSuchMethodDispatcher", "Await", "AwaitWithTypeCheck", "InitAsync", "Resume",
		"ReturnAsync", "ReturnAsyncNotFuture", "InitAsyncStar", "YieldAsyncStar", "ReturnAsyncStar",
		"InitSyncStar", "SuspendSyncStarAtStart", "SuspendSyncStarAtYield", "AsyncExceptionHandler", "CloneSuspendState",
		"FfiAsyncCallbackSend", "UnknownDartCode",
	} // count: 157
)

// VMStubNames returns the ordered VM_STUB_CODE_LIST expansion for a known
// Dart version, or nil if this version hasn't been verified yet. Index i
// names the i'th stub Code object in the VM-isolate snapshot's Code
// cluster (in cluster order) -- see the package doc comment above for the
// full derivation, verification method, and the deliberate +9 unnamed tail.
//
// The "3.10.7"/"3.11.0" cases below are matched against real Dart 3.10.9/
// 3.11.5 samples: internal/snapshot's version-hash table only records a
// version STRING per format-compatible snapshot hash, and a patch release
// within the same compatibility window shares an EARLIER release's hash
// (verified: a real 3.10.9 and 3.11.5 build's own snapshot hash matched
// the pre-existing "3.10.7"/"3.11.0" entries exactly) -- so
// info.Version.DartVersion reports the label, not the exact patch. The
// underlying stub/offset tables were independently re-derived and
// verified against the REAL 3.10.9/3.11.5/3.12.2 dart-lang/sdk tags this
// session, not merely assumed to carry over from the older label.
func VMStubNames(dartVersion string) []string {
	switch dartVersion {
	case "2.12.0":
		return stubNames2120
	case "2.17.6":
		return stubNames2176
	case "2.19.0":
		return stubNames2190
	case "3.0.5":
		return stubNames305
	case "3.1.0":
		return stubNames310
	case "3.2.5", "3.3.0":
		return stubNames325
	case "3.4.3":
		return stubNames343
	case "3.5.0":
		return stubNames350
	case "3.6.2":
		return stubNames362
	case "3.7.0":
		return stubNames370
	case "3.9.2":
		return stubNames392
	case "3.10.7":
		return stubNames3109
	case "3.11.0":
		return stubNames3115
	case "3.12.2":
		return stubNames3122
	case "3.13.0":
		return stubNames3130
	}
	return nil
}
