package main

import (
	"flag"
	"fmt"

	"aotopsy/internal/frida"
)

func cmdFridaImport(args []string) error {
	fs := flag.NewFlagSet("frida-import", flag.ContinueOnError)
	inPath := fs.String("in", "", "Frida stdout/event log generated by aotopsy hooks")
	staticDir := fs.String("static", "", "aotopsy static output directory")
	outDir := fs.String("out", "", "output directory for merged results (default: <static>_merged)")
	if err := parseNoPositionals(fs, args); err != nil {
		return err
	}
	if *inPath == "" || *staticDir == "" {
		return fmt.Errorf("--in and --static are required")
	}
	return frida.Import(frida.ImportOptions{
		InPath:    *inPath,
		StaticDir: *staticDir,
		OutDir:    *outDir,
	})
}
