// Package strutil provides shared string utility functions used across
// multiple aotopsy packages. Created to consolidate 4 different
// filename-sanitization implementations (P4-5 / G-004, H-032).
package strutil

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
	"unicode"
	"unicode/utf8"
)

const portableFilenameMaxBytes = 200

// SanitizeFilename maps an arbitrary recovered name to one portable path
// component. The output is safe under both Linux and Windows path semantics and
// is collision-resistant when sanitization, case-folding or truncation would
// otherwise merge distinct raw names.
//
// The readable part preserves printable Unicode. Invalid UTF-8 bytes,
// non-printable runes, Windows-reserved punctuation and spaces become '_'. A
// stable SHA-256 suffix is added whenever that mapping is lossy, whenever the
// raw name contains uppercase/non-ASCII text (Windows filesystems can fold
// those names), for reserved device/dot names, and on truncation. Legitimate
// U+FFFD is preserved; only an invalid one-byte UTF-8 decode is replaced.
//
// The 200-byte ceiling is deliberate: artifact paths are byte strings at the
// filesystem boundary. When a conventional extension is present, the identity
// suffix is inserted before it so .dart/.txt/etc. remain recognizable.
func SanitizeFilename(name string) string {
	raw := name
	var clean strings.Builder
	clean.Grow(len(name))
	changed := false
	// Reserve the suffix namespace generated by this package. Otherwise a lossy
	// raw name like `a:b` could map to `a_b_<hash>` and collide with a distinct,
	// already-safe raw name that literally has that spelling.
	disambiguate := hasGeneratedIdentitySuffix(name)
	for len(name) > 0 {
		r, size := utf8.DecodeRuneInString(name)
		if r == utf8.RuneError && size == 1 {
			// DecodeRuneInString returns (RuneError, 1) only for malformed UTF-8;
			// an actual encoded U+FFFD consumes three bytes and is valid data.
			clean.WriteByte('_')
			changed = true
			name = name[size:]
			continue
		}
		if !unicode.IsPrint(r) || r == ' ' || strings.ContainsRune(`/\:*?"<>|`, r) {
			clean.WriteByte('_')
			changed = true
		} else {
			clean.WriteRune(r)
			if r > unicode.MaxASCII || (r >= 'A' && r <= 'Z') {
				disambiguate = true
			}
		}
		name = name[size:]
	}

	s := clean.String()
	if strings.HasSuffix(s, ".") {
		for strings.HasSuffix(s, ".") {
			s = strings.TrimSuffix(s, ".") + "_"
		}
		changed = true
	}
	if s == "" {
		s = "_empty"
		changed = true
	}
	if s == "." || s == ".." || isWindowsReservedFilename(s) {
		s = "_" + s
		changed = true
	}

	if changed || disambiguate || len(s) > portableFilenameMaxBytes {
		s = addFilenameIdentitySuffix(s, raw)
	}
	return s
}

func isWindowsReservedFilename(name string) bool {
	base := name
	if i := strings.IndexByte(base, '.'); i >= 0 {
		base = base[:i]
	}
	upper := strings.ToUpper(strings.TrimRight(base, " "))
	switch upper {
	case "CON", "PRN", "AUX", "NUL", "CONIN$", "CONOUT$":
		return true
	}
	if len(upper) == 4 && (strings.HasPrefix(upper, "COM") || strings.HasPrefix(upper, "LPT")) && upper[3] >= '1' && upper[3] <= '9' {
		return true
	}
	if strings.HasPrefix(upper, "COM") || strings.HasPrefix(upper, "LPT") {
		suffix := strings.TrimPrefix(strings.TrimPrefix(upper, "COM"), "LPT")
		return suffix == "¹" || suffix == "²" || suffix == "³"
	}
	return false
}

func addFilenameIdentitySuffix(name, raw string) string {
	suffix := "_" + shortIdentityHash(raw)

	stem, ext := name, ""
	if dot := strings.LastIndexByte(name, '.'); dot > 0 && dot < len(name)-1 {
		candidate := name[dot:]
		if len(candidate)+len(suffix) < portableFilenameMaxBytes {
			stem, ext = name[:dot], candidate
		}
	}
	maxStem := portableFilenameMaxBytes - len(suffix) - len(ext)
	if maxStem < 1 {
		// This is only reachable for an unusually huge extension. Preserve the
		// identity rather than pretending the extension is more important than
		// the path component's uniqueness.
		ext = ""
		maxStem = portableFilenameMaxBytes - len(suffix)
		stem = name
	}
	stem = truncateValidUTF8(stem, maxStem)
	if stem == "" {
		stem = "_"
	}
	return stem + suffix + ext
}

func truncateValidUTF8(s string, maxBytes int) string {
	if maxBytes <= 0 {
		return ""
	}
	if len(s) <= maxBytes {
		return s
	}
	cut := maxBytes
	for cut > 0 && !utf8.ValidString(s[:cut]) {
		cut--
	}
	return s[:cut]
}

func shortIdentityHash(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:16])
}

func hasGeneratedIdentitySuffix(s string) bool {
	stem := s
	if dot := strings.LastIndexByte(stem, '.'); dot > 0 {
		stem = stem[:dot]
	}
	underscore := strings.LastIndexByte(stem, '_')
	if underscore < 0 || len(stem)-underscore-1 != 32 {
		return false
	}
	for i := underscore + 1; i < len(stem); i++ {
		c := stem[i]
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return false
		}
	}
	return true
}

// SanitizeR2FlagName makes a function identity usable as a radare2 flag name.
//
// Exact upstream source (radare2 commit 1c9077249a02d114b0bd524d5d2b6018ff9696c0,
// libr/util/name.c) defines r_name_check as [A-Za-z_:] for the first byte and
// [A-Za-z0-9_.:] thereafter. Keep '.' and ':' because upstream accepts them;
// dropping them destroyed meaningful owner/member distinctions.
//
// Every emitted flag also carries a stable 128-bit SHA-256-derived suffix of the
// raw name and its virtual address. This makes accidental collisions negligible
// for exporter identities: punctuation folding cannot merge Foo@1 with Foo_at_1,
// and two functions with the same display name at different VAs cannot redefine
// the same r2 flag unless the hash prefix itself collides.
func SanitizeR2FlagName(name string, va uint64) string {
	// Operator-only and Unicode-only names still carry semantic identity even
	// though r_name_check cannot represent their original bytes. Only a truly
	// empty/whitespace name is absent; every other raw name is retained through
	// the stable identity hash below.
	if strings.TrimSpace(name) == "" {
		return ""
	}
	raw := name
	name = strings.ReplaceAll(name, "@", "_at_")
	var b strings.Builder
	b.Grow(len(name))
	for _, r := range name {
		switch {
		case r == '_' || r == '.' || r == ':' ||
			(r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	// r_name_validate_first allows only [A-Za-z_:]. A dot is valid after the
	// first byte but not at position zero; digits have the same restriction.
	first := out[0]
	if !((first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') || first == '_' || first == ':') {
		out = "f_" + out
	}
	return fmt.Sprintf("%s_%s_%x", out, shortIdentityHash(raw), va)
}
