package vmtables

// Runtime-entry name tables for the Dart versions that had none.
//
// Thread caches an entry point for every RUNTIME_ENTRY_LIST and
// LEAF_RUNTIME_ENTRY_LIST member, laid out in declaration order, and
// mergeRuntimeEntries names them by index: offset = base + i*8. Without a
// table for a version, every runtime call in it renders as an unnamed
// THR.fNN -- which is not an error anywhere, just a permanently missing
// name. Nine versions were in that state (2.10.0 through 2.19.0 except
// 2.17.6, plus 3.13.0) until the SDK gate in runtimeentries_sdk_test.go
// counted them.
//
// Generated by `go run tools/extract_thr.go -emit-runtime-entries <tags>`.
// Names come from runtime_entry_list.h at each tag; the base offset is
// Thread_AllocateArray_entry_point_offset from that tag's
// runtime_offsets_extracted.h -- the first RUNTIME_ENTRY_LIST slot.
//
// Whether the LEAF block continues the runtime block is read from
// thread.h, not assumed. Through 2.19 the two DECLARE_MEMBERS expansions
// are adjacent, so the lists are stored flattened and installed with one
// merge. By 3.12.2 the LEAF expansion has moved down past
// exit_through_ffi_, leaving a gap of several hundred bytes, so 3.13.0
// keeps its two lists separate and takes its leaf base from
// Thread_DeoptimizeCopyFrame_entry_point_offset.
//
// Do not build one of these by copying a neighbouring version. 3.13.0
// inserts TypeError at index 45 of RUNTIME_ENTRY_LIST rather than
// appending it, so reusing 3.12.2's list would have shifted every name
// after it by 8 bytes -- plausibly, and with nothing to notice.

// Dart 2.10.0 (AllocateArray = 0x2e0), flattened.
var runtimeEntriesV2100 = []string{
	"AllocateArray", "AllocateContext", "AllocateObject",
	"AllocateSubtypeTestCache", "BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "GetFieldForDispatch", "ClosureArgumentsValid",
	"ResolveCallFunction", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs", "InterpretedInstanceCallMissHandler",
	"Instanceof", "SubtypeCheck", "TypeCheck",
	"NonBoolTypeError", "InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue", "InvokeNoSuchMethod",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "NullError", "NullErrorWithSelector",
	"NullCastError", "ArgumentNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException", "ReThrow",
	"StackOverflow", "AllocateMint", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField", "LateInitializationError",
	"CompileFunction", "CompileInterpretedFunction", "SwitchableCallMiss",
	"NotLoaded", "DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "MarkingStackBlockProcess", "RememberCard",
	"EnsureRememberedAndMarkingDeferred", "LibcPow", "DartModulo",
	"LibcFloor", "LibcCeil", "LibcTrunc",
	"LibcRound", "LibcCos", "LibcSin",
	"LibcTan", "LibcAcos", "LibcAsin",
	"LibcAtan", "LibcAtan2", "CaseInsensitiveCompareUCS2",
	"CaseInsensitiveCompareUTF16", "EnterSafepoint", "ExitSafepoint",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
}

// Dart 2.12.0 (AllocateArray = 0x2d0), flattened.
var runtimeEntriesV2120 = []string{
	"AllocateArray", "AllocateTypedData", "AllocateContext",
	"AllocateObject", "BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs", "Instanceof",
	"SubtypeCheck", "TypeCheck", "NonBoolTypeError",
	"InstantiateType", "InstantiateTypeArguments", "NoSuchMethodFromCallStub",
	"NoSuchMethodFromPrologue", "OptimizeInvokedFunction", "TraceICCall",
	"PatchStaticCall", "RangeError", "NullError",
	"NullErrorWithSelector", "NullCastError", "ArgumentNullError",
	"ArgumentError", "ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "StackOverflow", "AllocateMint",
	"Throw", "DeoptimizeMaterialize", "RewindPostDeopt",
	"UpdateFieldCid", "InitInstanceField", "InitStaticField",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError", "CompileFunction",
	"SwitchableCallMiss", "NotLoaded", "DeoptimizeCopyFrame",
	"DeoptimizeFillFrame", "StoreBufferBlockProcess", "MarkingStackBlockProcess",
	"RememberCard", "EnsureRememberedAndMarkingDeferred", "LibcPow",
	"DartModulo", "LibcFloor", "LibcCeil",
	"LibcTrunc", "LibcRound", "LibcCos",
	"LibcSin", "LibcTan", "LibcAcos",
	"LibcAsin", "LibcAtan", "LibcAtan2",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16", "EnterSafepoint",
	"ExitSafepoint", "EnterHandleScope", "ExitHandleScope",
	"AllocateHandle",
}

// Dart 2.13.0 (AllocateArray = 0x2d8), flattened.
var runtimeEntriesV2130 = []string{
	"AllocateArray", "AllocateTypedData", "AllocateContext",
	"AllocateObject", "BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs", "Instanceof",
	"SubtypeCheck", "TypeCheck", "NonBoolTypeError",
	"InstantiateType", "InstantiateTypeArguments", "NoSuchMethodFromCallStub",
	"NoSuchMethodFromPrologue", "OptimizeInvokedFunction", "TraceICCall",
	"PatchStaticCall", "RangeError", "NullError",
	"NullErrorWithSelector", "NullCastError", "ArgumentNullError",
	"DispatchTableNullError", "ArgumentError", "ArgumentErrorUnboxedInt64",
	"IntegerDivisionByZeroException", "ReThrow", "StackOverflow",
	"AllocateMint", "Throw", "DeoptimizeMaterialize",
	"RewindPostDeopt", "UpdateFieldCid", "InitInstanceField",
	"InitStaticField", "LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "SwitchableCallMiss", "NotLoaded",
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame", "StoreBufferBlockProcess",
	"MarkingStackBlockProcess", "RememberCard", "EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFloor",
	"LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan",
	"LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16", "EnterSafepoint",
	"ExitSafepoint", "EnterHandleScope", "ExitHandleScope",
	"AllocateHandle",
}

// Dart 2.14.0 (AllocateArray = 0x2d8), flattened.
var runtimeEntriesV2140 = []string{
	"AllocateArray", "AllocateMint", "AllocateDouble",
	"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
	"AllocateTypedData", "AllocateClosure", "AllocateContext",
	"AllocateObject", "BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs", "Instanceof",
	"SubtypeCheck", "TypeCheck", "NonBoolTypeError",
	"InstantiateType", "InstantiateTypeArguments", "NoSuchMethodFromCallStub",
	"NoSuchMethodFromPrologue", "OptimizeInvokedFunction", "TraceICCall",
	"PatchStaticCall", "RangeError", "NullError",
	"NullErrorWithSelector", "NullCastError", "ArgumentNullError",
	"DispatchTableNullError", "ArgumentError", "ArgumentErrorUnboxedInt64",
	"IntegerDivisionByZeroException", "ReThrow", "StackOverflow",
	"Throw", "DeoptimizeMaterialize", "RewindPostDeopt",
	"UpdateFieldCid", "InitInstanceField", "InitStaticField",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError", "CompileFunction",
	"SwitchableCallMiss", "NotLoaded", "DeoptimizeCopyFrame",
	"DeoptimizeFillFrame", "StoreBufferBlockProcess", "MarkingStackBlockProcess",
	"RememberCard", "EnsureRememberedAndMarkingDeferred", "LibcPow",
	"DartModulo", "LibcFloor", "LibcCeil",
	"LibcTrunc", "LibcRound", "LibcCos",
	"LibcSin", "LibcTan", "LibcAcos",
	"LibcAsin", "LibcAtan", "LibcAtan2",
	"LibcExp", "LibcLog", "CaseInsensitiveCompareUCS2",
	"CaseInsensitiveCompareUTF16", "EnterSafepoint", "ExitSafepoint",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"TsanLoadAcquire", "TsanStoreRelease",
}

// Dart 2.15.0 (AllocateArray = 0x2d8), flattened.
var runtimeEntriesV2150 = []string{
	"AllocateArray", "AllocateMint", "AllocateDouble",
	"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
	"AllocateTypedData", "AllocateClosure", "AllocateContext",
	"AllocateObject", "BoxDouble", "BreakpointRuntimeHandler",
	"SingleStepHandler", "CloneContext", "DoubleToInteger",
	"FixCallersTarget", "FixCallersTargetMonomorphic", "FixAllocationStubTarget",
	"InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs", "StaticCallMissHandlerOneArg",
	"StaticCallMissHandlerTwoArgs", "Instanceof", "SubtypeCheck",
	"TypeCheck", "NonBoolTypeError", "InstantiateType",
	"InstantiateTypeArguments", "NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "NullError", "NullErrorWithSelector",
	"NullCastError", "ArgumentNullError", "DispatchTableNullError",
	"ArgumentError", "ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "StackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField", "LateFieldAssignedDuringInitializationError",
	"LateFieldNotInitializedError", "CompileFunction", "SwitchableCallMiss",
	"NotLoaded", "DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "MarkingStackBlockProcess", "RememberCard",
	"EnsureRememberedAndMarkingDeferred", "LibcPow", "DartModulo",
	"LibcFloor", "LibcCeil", "LibcTrunc",
	"LibcRound", "LibcCos", "LibcSin",
	"LibcTan", "LibcAcos", "LibcAsin",
	"LibcAtan", "LibcAtan2", "LibcExp",
	"LibcLog", "CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint", "EnterHandleScope",
	"ExitHandleScope", "AllocateHandle", "TsanLoadAcquire",
	"TsanStoreRelease",
}

// Dart 2.16.0 (AllocateArray = 0x2e0), flattened.
var runtimeEntriesV2160 = []string{
	"AllocateArray", "AllocateMint", "AllocateDouble",
	"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
	"AllocateTypedData", "AllocateClosure", "AllocateContext",
	"AllocateObject", "BoxDouble", "BreakpointRuntimeHandler",
	"SingleStepHandler", "CloneContext", "DoubleToInteger",
	"FixCallersTarget", "FixCallersTargetMonomorphic", "FixAllocationStubTarget",
	"InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs", "StaticCallMissHandlerOneArg",
	"StaticCallMissHandlerTwoArgs", "Instanceof", "SubtypeCheck",
	"TypeCheck", "NonBoolTypeError", "InstantiateType",
	"InstantiateTypeArguments", "NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "NullError", "NullErrorWithSelector",
	"NullCastError", "ArgumentNullError", "DispatchTableNullError",
	"ArgumentError", "ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "StackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField", "LateFieldAssignedDuringInitializationError",
	"LateFieldNotInitializedError", "CompileFunction", "SwitchableCallMiss",
	"NotLoaded", "DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "MarkingStackBlockProcess", "RememberCard",
	"EnsureRememberedAndMarkingDeferred", "LibcPow", "DartModulo",
	"LibcFloor", "LibcCeil", "LibcTrunc",
	"LibcRound", "LibcCos", "LibcSin",
	"LibcTan", "LibcAcos", "LibcAsin",
	"LibcAtan", "LibcAtan2", "LibcExp",
	"LibcLog", "CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint", "EnterHandleScope",
	"ExitHandleScope", "AllocateHandle", "TsanLoadAcquire",
	"TsanStoreRelease",
}

// Dart 2.18.0 (AllocateArray = 0x310), flattened.
var runtimeEntriesV2180 = []string{
	"AllocateArray", "AllocateMint", "AllocateDouble",
	"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
	"AllocateTypedData", "AllocateClosure", "AllocateContext",
	"AllocateObject", "AllocateSuspendState", "BoxDouble",
	"BreakpointRuntimeHandler", "SingleStepHandler", "CloneContext",
	"CloneSuspendState", "DoubleToInteger", "FixCallersTarget",
	"FixCallersTargetMonomorphic", "FixAllocationStubTarget", "InlineCacheMissHandlerOneArg",
	"InlineCacheMissHandlerTwoArgs", "StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs",
	"Instanceof", "SubtypeCheck", "TypeCheck",
	"NonBoolTypeError", "InstantiateType", "InstantiateTypeArguments",
	"NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue", "OptimizeInvokedFunction",
	"TraceICCall", "PatchStaticCall", "RangeError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"ArgumentNullError", "DispatchTableNullError", "ArgumentError",
	"ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException", "ReThrow",
	"InterruptOrStackOverflow", "Throw", "DeoptimizeMaterialize",
	"RewindPostDeopt", "UpdateFieldCid", "InitInstanceField",
	"InitStaticField", "LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError",
	"CompileFunction", "ResumeFrame", "SwitchableCallMiss",
	"NotLoaded", "DeoptimizeCopyFrame", "DeoptimizeFillFrame",
	"StoreBufferBlockProcess", "MarkingStackBlockProcess", "RememberCard",
	"EnsureRememberedAndMarkingDeferred", "LibcPow", "DartModulo",
	"LibcFloor", "LibcCeil", "LibcTrunc",
	"LibcRound", "LibcCos", "LibcSin",
	"LibcTan", "LibcAcos", "LibcAsin",
	"LibcAtan", "LibcAtan2", "LibcExp",
	"LibcLog", "CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16",
	"EnterSafepoint", "ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"TsanLoadAcquire", "TsanStoreRelease",
}

// Dart 2.19.0 (AllocateArray = 0x328), flattened.
var runtimeEntriesV2190 = []string{
	"AllocateArray", "AllocateMint", "AllocateDouble",
	"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
	"AllocateTypedData", "AllocateClosure", "AllocateContext",
	"AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4",
	"BoxFloat64x2", "BreakpointRuntimeHandler", "SingleStepHandler",
	"CloneContext", "CloneSuspendState", "DoubleToInteger",
	"FixCallersTarget", "FixCallersTargetMonomorphic", "FixAllocationStubTarget",
	"InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs", "StaticCallMissHandlerOneArg",
	"StaticCallMissHandlerTwoArgs", "Instanceof", "SubtypeCheck",
	"TypeCheck", "NonBoolTypeError", "InstantiateType",
	"InstantiateTypeArguments", "NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"OptimizeInvokedFunction", "TraceICCall", "PatchStaticCall",
	"RangeError", "WriteError", "NullError",
	"NullErrorWithSelector", "NullCastError", "ArgumentNullError",
	"DispatchTableNullError", "ArgumentError", "ArgumentErrorUnboxedInt64",
	"IntegerDivisionByZeroException", "ReThrow", "InterruptOrStackOverflow",
	"Throw", "DeoptimizeMaterialize", "RewindPostDeopt",
	"UpdateFieldCid", "InitInstanceField", "InitStaticField",
	"LateFieldAssignedDuringInitializationError", "LateFieldNotInitializedError", "CompileFunction",
	"ResumeFrame", "SwitchableCallMiss", "NotLoaded",
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame", "StoreBufferBlockProcess",
	"MarkingStackBlockProcess", "RememberCard", "EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFloor",
	"LibcCeil", "LibcTrunc", "LibcRound",
	"LibcCos", "LibcSin", "LibcTan",
	"LibcAcos", "LibcAsin", "LibcAtan",
	"LibcAtan2", "LibcExp", "LibcLog",
	"CaseInsensitiveCompareUCS2", "CaseInsensitiveCompareUTF16", "EnterSafepoint",
	"ExitSafepoint", "ExitSafepointIgnoreUnwindInProgress", "EnterHandleScope",
	"ExitHandleScope", "AllocateHandle", "PropagateError",
	"MsanUnpoison", "MsanUnpoisonParam", "TsanLoadAcquire",
	"TsanStoreRelease", "TryDoubleAsInteger",
}

// Dart 3.13.0 (AllocateArray = 0x2f0, DeoptimizeCopyFrame = 0x720).
//
// TypeError sits at index 45, between NullCastError and ArgumentNullError.
// It is an insertion, not an append: every entry after it moved.
var runtimeEntriesV3130 = []string{
	"AllocateArray", "AllocateMint", "AllocateDouble",
	"AllocateFloat32x4", "AllocateFloat64x2", "AllocateInt32x4",
	"AllocateTypedData", "AllocateClosure", "AllocateContext",
	"AllocateObject", "AllocateRecord", "AllocateSmallRecord",
	"AllocateSuspendState", "BoxDouble", "BoxFloat32x4",
	"BoxFloat64x2", "BreakpointRuntimeHandler", "SingleStepHandler",
	"ResumptionBreakpointHandler", "CloneContext", "CloneSuspendState",
	"DoubleToInteger", "FixCallersTarget", "FixCallersTargetMonomorphic",
	"FixAllocationStubTarget", "InlineCacheMissHandlerOneArg", "InlineCacheMissHandlerTwoArgs",
	"StaticCallMissHandlerOneArg", "StaticCallMissHandlerTwoArgs", "Instanceof",
	"SubtypeCheck", "TypeCheck", "InstantiateType",
	"InstantiateTypeArguments", "NoSuchMethodFromCallStub", "NoSuchMethodFromPrologue",
	"NoSuchMethodError", "OptimizeInvokedFunction", "PatchStaticCall",
	"RangeError", "RangeErrorUnboxedInt64", "WriteError",
	"NullError", "NullErrorWithSelector", "NullCastError",
	"TypeError", "ArgumentNullError", "DispatchTableNullError",
	"ArgumentError", "ArgumentErrorUnboxedInt64", "IntegerDivisionByZeroException",
	"ReThrow", "InterruptOrStackOverflow", "Throw",
	"DeoptimizeMaterialize", "RewindPostDeopt", "UpdateFieldCid",
	"InitInstanceField", "InitStaticField", "StaticFieldAccessedWithoutIsolateError",
	"CheckedStoreIntoShared", "LateFieldAlreadyInitializedError", "LateFieldAssignedDuringInitializationError",
	"LateFieldNotInitializedError", "CompileFunction", "ResumeFrame",
	"SwitchableCallMiss", "NotLoaded", "FfiAsyncCallbackSend",
	"AllocateSubtypeTestCache", "GetFieldForDispatch", "AdjustArgumentsDesciptorForImplicitClosure",
	"ConvertToInstanceTypeArguments", "ClosureArgumentsValid", "ResolveCallFunction",
	"ResolveExternalCall", "FfiCall", "CheckFunctionArgumentTypes",
	"InterpretedInstanceCallMissHandler", "InvokeNoSuchMethod", "ResumeInterpreter",
	"InitializeSharedField", "FatalError", "EnsureDeeplyImmutable",
	"AllocateBytecodeCoverageArray",
}

var leafEntriesV3130 = []string{
	"DeoptimizeCopyFrame", "DeoptimizeFillFrame", "StoreBufferBlockProcess",
	"OldMarkingStackBlockProcess", "NewMarkingStackBlockProcess", "EnsureRememberedAndMarkingDeferred",
	"LibcPow", "DartModulo", "LibcFmod",
	"LibcFloor", "LibcCeil", "LibcTrunc",
	"LibcRound", "LibcCos", "LibcSin",
	"LibcTan", "LibcAcos", "LibcAsin",
	"LibcAtan", "LibcAtan2", "LibcExp",
	"LibcLog", "EnterSafepoint", "ExitSafepoint",
	"EnterHandleScope", "ExitHandleScope", "AllocateHandle",
	"PropagateError", "MsanUnpoison", "MsanUnpoisonParam",
	"TsanAtomic32Load", "TsanAtomic32Store", "TsanAtomic64Load",
	"TsanAtomic64Store", "SanRead1", "SanRead2",
	"SanRead4", "SanRead8", "SanRead16",
	"SanWrite1", "SanWrite2", "SanWrite4",
	"SanWrite8", "SanWrite16", "TsanFuncEntry",
	"TsanFuncExit", "TryDoubleAsInteger", "MemoryMove",
}

func init() {
	mergeRuntimeEntries(thrV2100, 0x2e0, runtimeEntriesV2100)
	mergeRuntimeEntries(thrV2120, 0x2d0, runtimeEntriesV2120)
	mergeRuntimeEntries(thrV2130, 0x2d8, runtimeEntriesV2130)
	mergeRuntimeEntries(thrV2140, 0x2d8, runtimeEntriesV2140)
	mergeRuntimeEntries(thrV2150, 0x2d8, runtimeEntriesV2150)
	mergeRuntimeEntries(thrV2160, 0x2e0, runtimeEntriesV2160)
	mergeRuntimeEntries(thrV2180, 0x310, runtimeEntriesV2180)
	mergeRuntimeEntries(thrV2190, 0x328, runtimeEntriesV2190)
	mergeRuntimeEntries(thrV3130, 0x2f0, runtimeEntriesV3130)
	mergeRuntimeEntries(thrV3130, 0x720, leafEntriesV3130)
}
