#!/usr/bin/env bash
# Regenerate COVERAGE.md by parsing every corpus sample present locally.
# Reproduce with: make coverage
set -euo pipefail
OUT="${1:-COVERAGE.md}"
ROWS="${COVROWS_FILE:-}"
TMP=""
if [ -z "$ROWS" ]; then
  TMP="$(mktemp)"; ROWS="$TMP"
  echo "Parsing every corpus sample present locally (this is heavy)..." >&2
  AOTOPSY_COVERAGE=1 go test ./internal/analysis/ -run TestCoverageCensus -count=1 -timeout 30m -v 2>&1 \
    | grep -oE "COVROW	.*" | sed 's/^COVROW	//' | sort -u > "$ROWS" || true
  # The row carries the sample's file name so `sort -u` dedupes repeated log
  # lines without collapsing distinct builds. It used to end at the function
  # counts, so two builds of the same version/arch that recovered the same
  # number of functions -- which the -gt- twins do, being the same binary
  # content -- became one row, and the headline under-reported the corpus by
  # however many such pairs existed.
fi
trap '[ -n "$TMP" ] && rm -f "$TMP"' EXIT

commit="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
gen_date="$(date -u +%Y-%m-%d)"
total="$(wc -l < "$ROWS" | tr -d ' ')"
fails="$(grep -c '	FAIL	' "$ROWS" || true)"
versions="$(cut -f1 "$ROWS" | sort -uV | wc -l | tr -d ' ')"

{
  echo "# Coverage — Snapshot Parse Across Dart Versions & Architectures"
  echo
  echo "Every registered corpus sample present locally, parsed end-to-end (ELF ->"
  echo "snapshot -> cluster alloc+fill -> instructions table -> disassembly). A clean"
  echo "parse across a version/arch means aotopsy models that snapshot format with"
  echo "**zero unknown-CID / cluster-desync errors**. Generated by \`make coverage\`"
  echo "(commit \`$commit\`, $gen_date)."
  echo
  echo "**${total} sample builds across ${versions} Dart versions parse cleanly on both"
  echo "architectures; ${fails} failures.**"
  echo
  echo "Snapshot support is structure-based (the header carries a git-derived hash, not"
  echo "a version number). Dart 3.13's serialization cluster set (49 clusters, incl. the"
  echo "new \`Bytecode\`/\`ApiError\`/\`UnwindError\`/\`LocalVarDescriptors\`) is fully"
  echo "recognized — verified against \`runtime/vm/app_snapshot.cc@3.13.2\` and by the"
  echo "clean 3.13.0 parse below."
  echo
  echo "| Dart version | arm64 | x64 | Functions (max) |"
  echo "|--------------|:-----:|:---:|-----------------|"
  for v in $(cut -f1 "$ROWS" | sort -uV); do
    a="—"; x="—"; maxfn=0
    while IFS=$'\t' read -r ver arch st fn rest; do
      [ "$ver" = "$v" ] || continue
      mark="✅"; [ "$st" = "FAIL" ] && mark="❌"
      case "$arch" in arm64) a="$mark";; x64) x="$mark";; esac
      [ "$fn" -gt "$maxfn" ] 2>/dev/null && maxfn="$fn"
    done < "$ROWS"
    printf '| %s | %s | %s | %s |\n' "$v" "$a" "$x" "$maxfn"
  done
  echo
  echo "## Method"
  echo
  echo "- Iterates \`samplecorpus.Registry\`; for each sample present on disk, runs the"
  echo "  full \`LoadContext\` pipeline and records success + recovered function count."
  echo "- A format aotopsy did not model would raise \`unknown CID\` and appear as ❌."
  echo "- Reproduce: \`make coverage\` (some versions have multiple build variants under"
  echo "  one version/arch cell; the max function count is shown)."
  echo "- Ground-truth name accuracy for the unstripped builds: see [BENCHMARK.md](BENCHMARK.md)."
} > "$OUT"
echo "Wrote $OUT ($total builds, $versions versions, $fails failures)." >&2
