#!/usr/bin/env bash
# Regenerate COVERAGE.md by parsing every corpus sample present locally.
# Reproduce with: make coverage
set -euo pipefail
OUT="${1:-COVERAGE.md}"
ROWS="${COVROWS_FILE:-}"
TMP=""
LOG=""
trap '[ -n "$TMP" ] && rm -f "$TMP"; [ -n "$LOG" ] && rm -f "$LOG"; true' EXIT
census_status=0
if [ -z "$ROWS" ]; then
  TMP="$(mktemp)"; ROWS="$TMP"
  LOG="$(mktemp)"
  echo "Parsing every corpus sample present locally (this is heavy)..." >&2
  # A failing census (FAIL rows) makes `go test` exit non-zero, and a log with
  # no COVROW line makes grep exit 1. Under pipefail either would kill the
  # script before the checks below can say WHY, so capture both explicitly.
  AOTOPSY_COVERAGE=1 go test ./internal/analysis/ -run TestCoverageCensus -count=1 -timeout 30m -v >"$LOG" 2>&1 || census_status=$?
  { grep -oE $'COVROW\t.*' "$LOG" || true; } | sed $'s/^COVROW\t//' | sort > "$ROWS"
  # The row carries the sample's file name, so a repeated log line is a
  # duplicate the filename check below rejects, while two distinct builds that
  # recovered the same function counts (the -gt- twins are the same binary
  # content) stay two rows. Rows used to end at the function counts and
  # `sort -u` merged such pairs, under-reporting the corpus.
fi

# The corpus manifest is the single source of the expected sample count; do not
# repeat the number here.
expected="$(grep -c . internal/samplecorpus/corpus_manifest.txt)"
total="$(wc -l < "$ROWS" | tr -d ' ')"
if grep -q $'\tFAIL\t' "$ROWS"; then
  echo "coverage census contains FAIL rows; refusing to publish" >&2
  grep $'\tFAIL\t' "$ROWS" >&2
  exit 1
fi
if [ "$census_status" -ne 0 ]; then
  echo "coverage census exited with status $census_status; refusing to publish" >&2
  [ -n "$LOG" ] && tail -n 40 "$LOG" >&2
  exit 1
fi
if [ "$total" -ne "$expected" ]; then
  echo "coverage census produced $total rows; expected exactly $expected" >&2
  exit 1
fi
if [ "$(cut -f6 "$ROWS" | sort -u | wc -l | tr -d ' ')" -ne "$expected" ]; then
  echo "coverage census contains duplicate or missing sample filenames" >&2
  exit 1
fi

commit="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
gen_date="$(date -u +%Y-%m-%d)"
fails="$(grep -c $'\tFAIL\t' "$ROWS" || true)"
versions="$(cut -f1 "$ROWS" | sort -uV | wc -l | tr -d ' ')"

{
  echo "# Coverage — Snapshot Parse Across Dart Versions & Architectures"
  echo
  echo "Every registered corpus sample present locally, parsed end-to-end (ELF ->"
  echo "snapshot -> cluster alloc+fill -> instructions table -> disassembly). A clean"
  echo "parse across a version/arch means aotopsy models that snapshot format with"
  echo "**zero unknown-CID / cluster-desync errors**. Generated by \`make coverage\`"
  echo "(commit \`$commit\`, $gen_date)."
  echo
  echo "**${total} sample builds across ${versions} Dart versions parse cleanly on both"
  echo "architectures; ${fails} failures.**"
  echo
  echo "Snapshot support is structure-based (the header carries a git-derived hash, not"
  echo "a version number). Dart 3.13's serialization cluster set (49 clusters, incl. the"
  echo "new \`Bytecode\`/\`ApiError\`/\`UnwindError\`/\`LocalVarDescriptors\`) is fully"
  echo "recognized — verified against \`runtime/vm/app_snapshot.cc@3.13.2\` and by the"
  echo "clean 3.13.0 parse below."
  echo
  echo "| Dart version | arm64 | x64 | Functions (max) |"
  echo "|--------------|:-----:|:---:|-----------------|"
  for v in $(cut -f1 "$ROWS" | sort -uV); do
    a="—"; x="—"; maxfn=0
    while IFS=$'\t' read -r ver arch st fn rest; do
      [ "$ver" = "$v" ] || continue
      mark="✅"; [ "$st" = "FAIL" ] && mark="❌"
      case "$arch" in arm64) a="$mark";; x64) x="$mark";; esac
      [ "$fn" -gt "$maxfn" ] 2>/dev/null && maxfn="$fn"
    done < "$ROWS"
    printf '| %s | %s | %s | %s |\n' "$v" "$a" "$x" "$maxfn"
  done
  echo
  echo "## Method"
  echo
  echo "- Iterates \`samplecorpus.Registry\`; for each sample present on disk, runs the"
  echo "  full \`LoadContext\` pipeline and records success + recovered function count."
  echo "- A format aotopsy did not model would raise \`unknown CID\` and appear as ❌."
  echo "- Reproduce: \`make coverage\` (some versions have multiple build variants under"
  echo "  one version/arch cell; the max function count is shown)."
  echo "- Ground-truth name accuracy for the unstripped builds: see [BENCHMARK.md](BENCHMARK.md)."
} > "$OUT"
echo "Wrote $OUT ($total builds, $versions versions, $fails failures)." >&2
