package frida

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateFridaScriptFromMeta(t *testing.T) {
	meta := FridaMetadata{
		DartVersion:        "3.9.2",
		Architecture:       "arm64",
		CompressedPointers: true,
		THRReg:             "x26",
		PPReg:              "x27",
		DTReg:              "x21",
		Functions: []FridaFunction{
			{Name: "User.login", VA: "0x1000", Size: 64},
		},
		UnresolvedBLRs: []FridaUnresolvedBLR{
			{VA: "0x1020", FromFunc: "User.login", Reg: "x0"},
		},
	}

	dir := t.TempDir()
	metaPath := filepath.Join(dir, "frida_metadata.json")
	data, err := json.Marshal(meta)
	if err != nil {
		t.Fatalf("marshal meta: %v", err)
	}
	if err := os.WriteFile(metaPath, data, 0644); err != nil {
		t.Fatalf("write meta: %v", err)
	}

	script := GenerateFridaScriptFromMeta(metaPath)
	if !strings.Contains(script, "Auto-generated by aotopsy frida-export") {
		t.Errorf("script missing header")
	}
	if !strings.Contains(script, "User.login") {
		t.Errorf("script missing function name")
	}
	if !strings.Contains(script, "0x1020") {
		t.Errorf("script missing BLR PC")
	}
}
