package frida

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

const testSourceSHA256 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

func finalizeTestMetadata(t *testing.T, meta FridaMetadata) FridaMetadata {
	t.Helper()
	meta.AnalyzerVersion = "test"
	meta.AnalyzerCommit = "deadbeef"
	meta.RuntimeIdentity = []RuntimeRegionDigest{{
		Kind: "executable", Offset: "0x0", Size: 4,
		SHA256: "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
	}}
	meta.Artifacts = []ArtifactDigest{
		DigestArtifact("provenance.json", []byte("provenance"), true),
		DigestArtifact("functions.jsonl", []byte("functions"), true),
		DigestArtifact("call_edges.jsonl", []byte("edges"), true),
		DigestArtifact("dispatch_table.jsonl", nil, false),
		DigestArtifact("string_refs.jsonl", nil, false),
		DigestArtifact("evidence.jsonl", nil, false),
	}
	if err := FinalizeMetadata(&meta); err != nil {
		t.Fatal(err)
	}
	return meta
}

func TestGenerateFridaScriptFromMeta(t *testing.T) {
	meta := FridaMetadata{
		SchemaVersion:      MetadataSchemaVersion,
		SourceSHA256:       testSourceSHA256,
		SourceSize:         1234,
		ModuleName:         "libapp.so",
		DartVersion:        "3.9.2",
		Architecture:       "arm64",
		CompressedPointers: true,
		PointerSize:        4,
		THRReg:             "x26",
		PPReg:              "x27",
		DTReg:              "x21",
		HeapBaseMode:       "heap_bits",
		HeapBaseReg:        "x28",
		HeaderBitOffset:    12,
		HeaderBitWidth:     20,
		Functions: []FridaFunction{
			{Name: "User.login", VA: "0x1000", Size: 64},
		},
		CallProbes: []FridaCallProbe{
			{VA: "0x1020", FromFunc: "User.login", TargetKind: "register", Reg: "x0"},
		},
		THRFields: map[int]string{0x70: "later", 0x48: "earlier"},
	}
	meta = finalizeTestMetadata(t, meta)

	script, err := GenerateFridaScript(meta)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(script, "Auto-generated by aotopsy frida-export") {
		t.Errorf("script missing header")
	}
	if !strings.Contains(script, "User.login") {
		t.Errorf("script missing function name")
	}
	if !strings.Contains(script, "0x1020") {
		t.Errorf("script missing BLR PC")
	}
	if !strings.Contains(script, runtimeEventPrefix) {
		t.Errorf("script missing machine-readable runtime event contract")
	}
	if !strings.Contains(script, "Process.attachThreadObserver") || !strings.Contains(script, "Process.getCurrentThreadId()") {
		t.Errorf("script still lacks supported Frida thread-name tracking")
	}
	if strings.Contains(script, "Thread.currentName") {
		t.Errorf("script uses removed/unsupported Thread.currentName API")
	}
	if strings.Index(script, `0x48: "earlier"`) > strings.Index(script, `0x70: "later"`) {
		t.Errorf("THR field emission is not deterministic/sorted")
	}
	if script2, err := GenerateFridaScript(meta); err != nil || script2 != script {
		t.Errorf("same metadata generated different Frida JavaScript")
	}
	if strings.Contains(script, "via: s.via") {
		t.Fatal("generated runtime dispatch event contains field rejected by importer schema")
	}
	for _, want := range []string{
		"new Checksum('sha256')",
		"Process.arch !== META.arch",
		"cursor.readByteArray(take)",
		"measuredRegionSHA256 !== region.sha256.toLowerCase()",
		"event.generation_id = META.generationID",
		"function_va: h.addr",
	} {
		if !strings.Contains(script, want) {
			t.Errorf("script missing runtime trust-boundary check %q", want)
		}
	}
	if strings.Contains(script, "MAX_HOOKS") || strings.Contains(script, "MAX_PROBES") {
		t.Fatal("runtime script still applies an unbound hook/probe cap")
	}
	if strings.Contains(script, "source_sha256: META.sourceSHA256") {
		t.Fatal("runtime event still self-asserts the static source hash instead of measured identity")
	}
}

func TestNewCallProbeStructuredTargets(t *testing.T) {
	reg, ok := NewCallProbe("0x100", "F", "X16", "")
	if !ok || reg.TargetKind != "register" || reg.Reg != "x16" {
		t.Fatalf("register probe = %+v,%v", reg, ok)
	}
	mem, ok := NewCallProbe("0x200", "F", "[RAX+RCX*8+0xd700]", "dispatch_table")
	if !ok || mem.TargetKind != "x86_mem" || mem.BaseReg != "rax" || mem.IndexReg != "rcx" || mem.Scale != 8 || mem.Disp != 0xd700 {
		t.Fatalf("x86 memory probe = %+v,%v", mem, ok)
	}
	if _, ok := NewCallProbe("0x300", "F", "[not parseable", ""); ok {
		t.Fatal("malformed memory target produced a runtime probe")
	}
	neg, ok := NewCallProbe("0x301", "F", "[RAX+RCX*8-0x20]", "")
	if !ok || neg.Disp != -0x20 {
		t.Fatalf("negative displacement probe = %+v,%v", neg, ok)
	}
	for _, target := range []string{"[RAX+0x7fffffff]", "[RAX-0x80000000]"} {
		if _, ok := NewCallProbe("0x302", "F", target, ""); !ok {
			t.Fatalf("valid signed disp32 target %q was rejected", target)
		}
	}
	for _, target := range []string{"[RAX+0x80000000]", "[RAX-0x80000001]"} {
		if _, ok := NewCallProbe("0x303", "F", target, ""); ok {
			t.Fatalf("impossible x86 displacement target %q produced a runtime probe", target)
		}
	}
}

func TestX86MemoryProbeScriptEvaluatesAndDereferencesAddress(t *testing.T) {
	meta := FridaMetadata{
		SchemaVersion:   MetadataSchemaVersion,
		SourceSHA256:    testSourceSHA256,
		SourceSize:      1234,
		ModuleName:      "libapp.so",
		DartVersion:     "3.12.2",
		Architecture:    "x64",
		PointerSize:     8,
		THRReg:          "r14",
		PPReg:           "r15",
		DTReg:           "rax",
		HeapBaseMode:    "none",
		HeaderBitOffset: 12,
		HeaderBitWidth:  20,
		CallProbes: []FridaCallProbe{{
			VA: "0x100", FromFunc: "F", TargetKind: "x86_mem",
			BaseReg: "rax", IndexReg: "rcx", Scale: 8, Disp: 0xd700,
		}},
	}
	meta = finalizeTestMetadata(t, meta)
	s, err := GenerateFridaScript(meta)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"site.targetKind === 'x86_mem'",
		"indexVal.shl(3)",
		"safeReadPtr(ea)",
		"targetModule.base.equals(base)",
		"target has no owning module; skipping runtime resolution",
	} {
		if !strings.Contains(s, want) {
			t.Errorf("script missing %q", want)
		}
	}
}

func TestValidateMetadataRejectsArchitectureAndPointerLayoutDrift(t *testing.T) {
	meta := FridaMetadata{
		SchemaVersion:   MetadataSchemaVersion,
		SourceSHA256:    testSourceSHA256,
		SourceSize:      1234,
		ModuleName:      "libapp.so",
		DartVersion:     "3.12.2",
		Architecture:    "arm64",
		PointerSize:     8,
		THRReg:          "x26",
		PPReg:           "x27",
		DTReg:           "x21",
		HeapBaseMode:    "none",
		HeaderBitOffset: 12,
		HeaderBitWidth:  20,
	}
	meta = finalizeTestMetadata(t, meta)

	wrongArchReg := meta
	wrongArchReg.THRReg = "r14"
	if err := ValidateMetadata(wrongArchReg); err == nil {
		t.Fatal("ARM64 metadata accepted an x64 context register")
	}

	wrongPointerSize := meta
	wrongPointerSize.CompressedPointers = true
	if err := ValidateMetadata(wrongPointerSize); err == nil {
		t.Fatal("compressed-pointer metadata accepted an 8-byte pointer size")
	}

	unsafeSourceSize := meta
	unsafeSourceSize.SourceSize = int64(maxSafeJSInteger) + 1
	if err := ValidateMetadata(unsafeSourceSize); err == nil {
		t.Fatal("source size above exact JavaScript integer range was accepted")
	}
}

func TestGenerateFridaScriptQuotesMetadataAndRejectsUnsafeOffsets(t *testing.T) {
	meta := FridaMetadata{
		SchemaVersion:   MetadataSchemaVersion,
		SourceSHA256:    testSourceSHA256,
		SourceSize:      1234,
		ModuleName:      "libapp.so",
		DartVersion:     "3.12.2",
		Architecture:    "arm64",
		PointerSize:     8,
		THRReg:          "x26",
		PPReg:           "x27",
		DTReg:           "x21",
		HeapBaseMode:    "none",
		HeaderBitOffset: 12,
		HeaderBitWidth:  20,
		Functions: []FridaFunction{{
			VA: "0x1000", Name: "x'; globalThis.PWNED=1;//", Size: 4,
		}},
	}
	meta = finalizeTestMetadata(t, meta)
	s, err := GenerateFridaScript(meta)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(s, `"x'; globalThis.PWNED=1;//"`) {
		t.Fatalf("hostile name was not encoded as a JSON/JavaScript string: %s", s)
	}
	if strings.Contains(s, `: 'x'; globalThis.PWNED`) {
		t.Fatalf("hostile name escaped JavaScript string context: %s", s)
	}
	meta.Functions[0].VA = "0x20000000000001"
	if _, err := GenerateFridaScript(meta); err == nil {
		t.Fatal("offset above exact JavaScript integer range was accepted")
	}
}

func TestDispatchClassIDRegisterUsesVersionedABI(t *testing.T) {
	tests := []struct {
		arch, version, want string
	}{
		{"arm64", "2.12.0", ""},
		{"arm64", "2.13.0", "x0"},
		{"arm64", "3.12.2", "x0"},
		{"x64", "2.12.0", "rcx"},
	}
	for _, tt := range tests {
		if got := DispatchClassIDRegister(tt.arch, tt.version); got != tt.want {
			t.Errorf("DispatchClassIDRegister(%q,%q)=%q, want %q", tt.arch, tt.version, got, tt.want)
		}
	}
}

func TestFinalizeMetadataBindsExactInstalledSubset(t *testing.T) {
	meta := FridaMetadata{
		SchemaVersion:   MetadataSchemaVersion,
		SourceSHA256:    testSourceSHA256,
		SourceSize:      1234,
		ModuleName:      "libapp.so",
		DartVersion:     "3.12.2",
		Architecture:    "x64",
		PointerSize:     8,
		THRReg:          "r14",
		PPReg:           "r15",
		DTReg:           "rax",
		HeapBaseMode:    "none",
		HeaderBitOffset: 12,
		HeaderBitWidth:  20,
	}
	for i := 0; i < maxInstalledFunctions+5; i++ {
		meta.Functions = append(meta.Functions, FridaFunction{VA: "0x" + strconv.FormatInt(int64(0x1000+i), 16), Name: "F" + strconv.Itoa(i), Size: 4})
	}
	for i := 0; i < maxInstalledCallProbes+5; i++ {
		meta.CallProbes = append(meta.CallProbes, FridaCallProbe{VA: "0x" + strconv.FormatInt(int64(0x2000+i), 16), FromFunc: "F0", TargetKind: "register", Reg: "rax"})
	}
	meta = finalizeTestMetadata(t, meta)
	if len(meta.InstalledFunctions) != maxInstalledFunctions || len(meta.InstalledCallProbes) != maxInstalledCallProbes {
		t.Fatalf("installed subset sizes=(%d,%d), want (%d,%d)", len(meta.InstalledFunctions), len(meta.InstalledCallProbes), maxInstalledFunctions, maxInstalledCallProbes)
	}
	if meta.GenerationID == "" {
		t.Fatal("metadata generation binding is empty")
	}
	original := meta.GenerationID
	meta.Artifacts[1] = DigestArtifact("functions.jsonl", []byte("different generation"), true)
	meta.GenerationID = ""
	changed, err := ComputeGenerationID(BindingFromMetadata(meta))
	if err != nil {
		t.Fatal(err)
	}
	if changed == original {
		t.Fatal("generation id did not change when a consumed artifact digest changed")
	}
}

func TestGeneratedHookDoesNotGuessArgumentRegisters(t *testing.T) {
	s := GenerateFridaScriptWithOptions("libapp.so", true,
		[]FridaHook{{VA: 0x1000, Name: "StackCalled"}}, nil, FridaOptions{})
	if strings.Contains(s, "DEFAULT_REGS") {
		t.Fatal("generated script still contains an architecture-wide fallback argument register set")
	}
	if !strings.Contains(s, `{ va: 0x1000, name: "StackCalled", regs: [] }`) {
		t.Fatalf("hook without proven register args should emit an empty register list:\n%s", s)
	}
}

func TestLegacyGeneratorQuotesModuleNameInHeader(t *testing.T) {
	s := GenerateFridaScriptWithOptions("libapp\nconsole.log('injected').so", true,
		[]FridaHook{{VA: 0x1000, Name: "F"}}, nil, FridaOptions{})
	if strings.Contains(s, "// Target module: libapp\nconsole.log('injected').so") {
		t.Fatal("module basename escaped the generated comment")
	}
	if !strings.Contains(s, `// Target module: "libapp\nconsole.log('injected').so"`) {
		t.Fatalf("module basename was not safely quoted in header:\n%s", s)
	}
}

func TestWriteFridaScriptRejectsDestructiveAliases(t *testing.T) {
	dir := t.TempDir()
	lib := filepath.Join(dir, "libapp.so")
	const original = "source-binary"
	if err := os.WriteFile(lib, []byte(original), 0o600); err != nil {
		t.Fatal(err)
	}
	hooks := []FridaHook{{VA: 0x1000, Name: "F"}}
	if err := WriteFridaScript(lib, dir, lib, true, hooks, nil, FridaOptions{}); err == nil {
		t.Fatal("Frida script output was allowed to overwrite source binary")
	}
	if b, err := os.ReadFile(lib); err != nil || string(b) != original {
		t.Fatalf("source binary changed after rejected alias: %q, %v", b, err)
	}

	combined := filepath.Join(dir, "combined.dart")
	if err := os.WriteFile(combined, []byte("previous decompile"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := WriteFridaScript(combined, dir, lib, true, hooks, nil, FridaOptions{}); err == nil {
		t.Fatal("Frida script output was allowed to overwrite combined.dart")
	}
	if b, err := os.ReadFile(combined); err != nil || string(b) != "previous decompile" {
		t.Fatalf("combined.dart changed after rejected alias: %q, %v", b, err)
	}
}
