package frida

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"aotopsy/internal/cli"
	"aotopsy/internal/disasm"
	"aotopsy/internal/evidence"
	"aotopsy/internal/jsonutil"
	"aotopsy/internal/output"
)

const runtimeEventPrefix = "AOTOPSY_EVENT "

const (
	maxRuntimeLogBytes  = int64(64 << 20)
	maxRuntimeEvents    = 500_000
	maxRuntimeEventLine = 1 << 20
	maxProvenanceBytes  = int64(1 << 20)
)

// runtimeEvent is the one and only export→run→import wire record. Generated
// scripts print one tagged JSON object per runtime observation; redirect Frida's
// stdout to a file and pass that file to frida-import. Ordinary Frida/console
// chatter is deliberately ignored.
type runtimeEvent struct {
	SchemaVersion int    `json:"schema_version"`
	GenerationID  string `json:"generation_id"`
	SourceSHA256  string `json:"source_sha256"`
	SourceSize    int64  `json:"source_size"`
	Architecture  string `json:"architecture"`
	Type          string `json:"type"`
	Name          string `json:"name,omitempty"`
	FunctionVA    string `json:"function_va,omitempty"`
	BLRAddr       string `json:"blr_addr,omitempty"`
	FromFunc      string `json:"from_func,omitempty"`
	TargetVA      string `json:"target_va,omitempty"`
	TargetName    string `json:"target_name,omitempty"`
	TargetModule  string `json:"target_module,omitempty"`
	ClassID       int    `json:"class_id,omitempty"`
}

type staticProvenance struct {
	Source             string          `json:"source"`
	SourceName         string          `json:"source_name"`
	SHA256             string          `json:"sha256"`
	Size               int64           `json:"size"`
	Arch               string          `json:"arch"`
	DartVersion        string          `json:"dart_version"`
	CompressedPointers bool            `json:"compressed_pointers"`
	Build              json.RawMessage `json:"build"`
}

type staticRuntimeSite struct {
	fromFunc   string
	via        string
	classIDReg string
}

type staticGeneration struct {
	provenance staticProvenance
	edges      []disasm.CallEdgeRecord
	functions  []disasm.FuncRecord
	binding    FridaBinding
}

type resolutionAggregate struct {
	targets      map[string]int
	classIDs     map[int]struct{}
	functions    map[string]struct{}
	observations int
}

func CmdFridaImport(args []string) error {
	fs := flag.NewFlagSet("frida-import", flag.ContinueOnError)
	inPath := fs.String("in", "", "Frida stdout/event log generated by aotopsy hooks")
	staticDir := fs.String("static", "", "aotopsy static output directory")
	outDir := fs.String("out", "", "output directory for merged results (default: <static>_merged)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *inPath == "" || *staticDir == "" {
		return fmt.Errorf("--in and --static are required")
	}
	if *outDir == "" {
		*outDir = *staticDir + "_merged"
	}

	staticAbs, err := filepath.Abs(*staticDir)
	if err != nil {
		return fmt.Errorf("frida-import: resolve static dir: %w", err)
	}
	outAbs, err := filepath.Abs(*outDir)
	if err != nil {
		return fmt.Errorf("frida-import: resolve output dir: %w", err)
	}
	inAbs, err := filepath.Abs(*inPath)
	if err != nil {
		return fmt.Errorf("frida-import: resolve runtime log: %w", err)
	}
	if staticAbs != outAbs {
		overlap, err := output.PathsOverlap(staticAbs, outAbs)
		if err != nil {
			return fmt.Errorf("frida-import: compare static/output paths: %w", err)
		}
		if overlap {
			return fmt.Errorf("frida-import: --static and --out must not contain one another")
		}
	}
	insideOut, err := output.ContainsPath(outAbs, inAbs)
	if err != nil {
		return fmt.Errorf("frida-import: compare runtime-log/output paths: %w", err)
	}
	if insideOut {
		return fmt.Errorf("frida-import: --in must not be inside --out because publishing the merged generation would replace the input log")
	}

	generation, err := readStaticGeneration(staticAbs)
	if err != nil {
		return err
	}
	prov := generation.provenance
	edges := generation.edges
	funcs := generation.functions
	events, err := readRuntimeEventLog(inAbs, generation.binding)
	if err != nil {
		return err
	}

	knownFunctions := make(map[string]struct{}, len(funcs))
	knownFunctionPCs := make(map[string]string, len(funcs))
	for _, f := range funcs {
		knownFunctions[f.Name] = struct{}{}
		pc, err := canonicalRuntimeHex(f.PC)
		if err != nil {
			return fmt.Errorf("frida-import: static function %q has invalid pc %q: %w", f.Name, f.PC, err)
		}
		if old, exists := knownFunctionPCs[pc]; exists && old != f.Name {
			return fmt.Errorf("frida-import: conflicting static functions at %s: %q and %q", pc, old, f.Name)
		}
		knownFunctionPCs[pc] = f.Name
	}
	installedFunctions := make(map[string]string, len(generation.binding.InstalledFunctions))
	for _, f := range generation.binding.InstalledFunctions {
		pc, err := canonicalRuntimeHex(f.VA)
		if err != nil {
			return fmt.Errorf("frida-import: installed function %q has invalid pc %q: %w", f.Name, f.VA, err)
		}
		if old, exists := installedFunctions[pc]; exists && old != f.Name {
			return fmt.Errorf("frida-import: conflicting installed functions at %s: %q and %q", pc, old, f.Name)
		}
		installedFunctions[pc] = f.Name
	}
	sites := make(map[string]staticRuntimeSite, len(generation.binding.InstalledBLRs))
	for _, p := range generation.binding.InstalledBLRs {
		pc, err := canonicalRuntimeHex(p.VA)
		if err != nil {
			return fmt.Errorf("frida-import: installed probe has invalid pc %q: %w", p.VA, err)
		}
		site := staticRuntimeSite{fromFunc: p.FromFunc, via: p.Via, classIDReg: p.ClassIDReg}
		if old, exists := sites[pc]; exists && old != site {
			return fmt.Errorf("frida-import: conflicting installed runtime sites at %s", pc)
		}
		sites[pc] = site
	}

	resolutions := make(map[string]*resolutionAggregate)
	runtimeCalls := make(map[string]int)
	for _, ev := range events {
		switch ev.Type {
		case "function_enter":
			if ev.Name == "" || ev.FunctionVA == "" {
				return fmt.Errorf("frida-import: function_enter event missing name/function_va")
			}
			pc, err := canonicalRuntimeHex(ev.FunctionVA)
			if err != nil {
				return fmt.Errorf("frida-import: function_enter has invalid function_va %q: %w", ev.FunctionVA, err)
			}
			installedName, ok := installedFunctions[pc]
			if !ok || installedName != ev.Name {
				return fmt.Errorf("frida-import: function_enter %s/%q was not in the exact installed hook set", pc, ev.Name)
			}
			runtimeCalls[ev.Name]++
		case "dispatch":
			if ev.BLRAddr == "" {
				return fmt.Errorf("frida-import: dispatch event missing blr_addr")
			}
			pc, err := canonicalRuntimeHex(ev.BLRAddr)
			if err != nil {
				return fmt.Errorf("frida-import: dispatch event has invalid blr_addr %q: %w", ev.BLRAddr, err)
			}
			site, ok := sites[pc]
			if !ok {
				return fmt.Errorf("frida-import: dispatch event references site %s that was not in the exact installed probe set", pc)
			}
			if ev.FromFunc == "" || ev.FromFunc != site.fromFunc {
				return fmt.Errorf("frida-import: dispatch site %s function %q does not match static %q", ev.BLRAddr, ev.FromFunc, site.fromFunc)
			}
			if ev.ClassID < -1 || int64(ev.ClassID) > 1<<31-1 {
				return fmt.Errorf("frida-import: site %s supplied impossible class id %d", pc, ev.ClassID)
			}
			if ev.ClassID > 0 && (site.via != "dispatch_table" || site.classIDReg == "") {
				return fmt.Errorf("frida-import: site %s supplied class id %d without a generation-approved CID register", pc, ev.ClassID)
			}
			target, err := validateRuntimeTarget(ev, prov, knownFunctions, knownFunctionPCs)
			if err != nil {
				return fmt.Errorf("frida-import: dispatch site %s target: %w", ev.BLRAddr, err)
			}
			a := resolutions[pc]
			if a == nil {
				a = &resolutionAggregate{targets: map[string]int{}, classIDs: map[int]struct{}{}, functions: map[string]struct{}{}}
				resolutions[pc] = a
			}
			a.targets[target]++
			if ev.FromFunc != "" {
				a.functions[ev.FromFunc] = struct{}{}
			}
			if ev.ClassID > 0 {
				a.classIDs[ev.ClassID] = struct{}{}
			}
			a.observations++
		default:
			return fmt.Errorf("frida-import: unsupported event type %q", ev.Type)
		}
	}

	resolvedEdges := 0
	confirmedEdges := 0
	for i := range edges {
		e := &edges[i]
		if e.Kind != "blr" && e.Kind != "call_indirect" {
			continue
		}
		pc, err := canonicalRuntimeHex(e.FromPC)
		if err != nil {
			return fmt.Errorf("frida-import: static indirect edge has invalid from_pc %q: %w", e.FromPC, err)
		}
		a := resolutions[pc]
		if a == nil {
			continue
		}
		targets := sortedTargetKeys(a.targets)
		e.RuntimeResolved = true
		e.RuntimeTargets = targets
		e.RuntimeObservations = a.observations
		e.RuntimeClassIDs = sortedIntKeys(a.classIDs)
		e.RuntimeConfirmed = true
		e.RuntimeCallCount = a.observations
		resolvedEdges++
		confirmedEdges++

		// Only fill the ordinary static target fields when static analysis had no
		// answer at all. A runtime observation narrows what happened in THIS run;
		// it must not erase an existing static polymorphic candidate set.
		if e.Target == "" && len(e.Targets) == 0 {
			if len(targets) == 1 {
				e.Target = targets[0]
			} else if len(targets) > 1 {
				e.Targets = append([]string(nil), targets...)
				e.Candidates = len(targets)
			}
		}
	}

	tx, err := output.BeginDirTransaction(outAbs)
	if err != nil {
		return fmt.Errorf("frida-import: begin output transaction: %w", err)
	}
	committed := false
	defer func() {
		if !committed {
			tx.Abort()
		}
	}()
	stage := tx.StageDir()
	if err := output.CloneTree(staticAbs, stage); err != nil {
		return fmt.Errorf("frida-import: clone static generation: %w", err)
	}
	stagedGeneration, err := readStaticGeneration(stage)
	if err != nil {
		return fmt.Errorf("frida-import: validate cloned static generation: %w", err)
	}
	if stagedGeneration.binding.GenerationID != generation.binding.GenerationID {
		return fmt.Errorf("frida-import: static generation changed while it was being cloned")
	}
	for _, name := range []string{BindingFileName, "frida_metadata.json", "frida_hooks.js"} {
		if err := os.Remove(filepath.Join(stage, name)); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("frida-import: remove stale Frida export artifact %s: %w", name, err)
		}
	}
	if _, err := jsonutil.WriteJSONLFile(filepath.Join(stage, "call_edges.jsonl"), edges); err != nil {
		return fmt.Errorf("frida-import: write merged edges: %w", err)
	}
	runtimeResolutions := flattenRuntimeResolutions(resolutions)
	coverage, evidenceMerged, err := mergeRuntimeEvidence(stage, stage, runtimeResolutions)
	if err != nil {
		return err
	}

	report := fmt.Sprintf(
		"Frida Import Report\n===================\n\nStatic output: %s\nFrida event log: %s\nMerged output: %s\nGeneration ID: %s\n\nRuntime events: %d\nFunction entries observed: %d\nDispatch sites observed: %d\nIndirect edges enriched: %d\nRuntime-confirmed source edges: %d\nEvidence merged: %t\nEvidence coverage: static_only=%d runtime_only=%d match=%d conflict=%d indeterminate=%d runtime_confirmed=%d invalid_runtime=%d\n",
		*staticDir, *inPath, *outDir, generation.binding.GenerationID, len(events), totalRuntimeCalls(runtimeCalls), len(resolutions), resolvedEdges, confirmedEdges,
		evidenceMerged, coverage.StaticOnly, coverage.RuntimeOnly, coverage.BothMatch, coverage.BothConflict, coverage.BothIndeterminate, coverage.RuntimeConfirmed, coverage.InvalidRuntime,
	)
	if err := output.WriteFileAtomic(filepath.Join(stage, "frida_import_report.txt"), []byte(report), 0o644); err != nil {
		return fmt.Errorf("frida-import: write report: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("frida-import: publish merged generation: %w", err)
	}
	committed = true

	logger := cli.NewLogger(os.Stderr, false)
	logger.Printf("Frida import complete: %s\n", *outDir)
	logger.Printf("  indirect edges enriched: %d\n", resolvedEdges)
	return nil
}

func flattenRuntimeResolutions(aggregates map[string]*resolutionAggregate) []evidence.RuntimeResolution {
	pcs := make([]string, 0, len(aggregates))
	for pc := range aggregates {
		pcs = append(pcs, pc)
	}
	sort.Strings(pcs)
	var out []evidence.RuntimeResolution
	for _, pc := range pcs {
		a := aggregates[pc]
		if a == nil {
			continue
		}
		targets := sortedTargetKeys(a.targets)
		functions := make([]string, 0, len(a.functions))
		for fn := range a.functions {
			functions = append(functions, fn)
		}
		sort.Strings(functions)
		if len(functions) == 0 {
			functions = []string{""}
		}
		for _, fn := range functions {
			for _, target := range targets {
				out = append(out, evidence.RuntimeResolution{PC: pc, Function: fn, TargetName: target})
			}
		}
	}
	return out
}

func mergeRuntimeEvidence(staticDir, outDir string, runtime []evidence.RuntimeResolution) (evidence.CoverageReport, bool, error) {
	staticPath := filepath.Join(staticDir, "evidence.jsonl")
	if _, err := os.Stat(staticPath); err != nil {
		if os.IsNotExist(err) {
			return evidence.NewCollector().Coverage(runtime), false, nil
		}
		return evidence.CoverageReport{}, false, fmt.Errorf("frida-import: stat evidence.jsonl: %w", err)
	}
	records, err := jsonutil.ReadJSONL[evidence.Evidence](staticPath, jsonutil.StandardLimits)
	if err != nil {
		return evidence.CoverageReport{}, false, fmt.Errorf("frida-import: read evidence.jsonl: %w", err)
	}
	c := evidence.NewCollectorFromRecords(records)
	c.MergeRuntime(runtime)
	coverage := c.Coverage(runtime)
	if err := c.WriteJSONL(filepath.Join(outDir, "evidence.jsonl")); err != nil {
		return evidence.CoverageReport{}, false, fmt.Errorf("frida-import: write enriched evidence.jsonl: %w", err)
	}
	if err := output.WriteJSONFile(filepath.Join(outDir, "runtime_coverage.json"), coverage); err != nil {
		return evidence.CoverageReport{}, false, fmt.Errorf("frida-import: write runtime coverage: %w", err)
	}
	return coverage, true, nil
}

func readRuntimeEventLog(path string, binding FridaBinding) ([]runtimeEvent, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("frida-import: open runtime log: %w", err)
	}
	defer func() { _ = f.Close() }()
	if st, err := f.Stat(); err != nil {
		return nil, fmt.Errorf("frida-import: stat runtime log: %w", err)
	} else if st.Size() > maxRuntimeLogBytes {
		return nil, fmt.Errorf("frida-import: runtime log is %d bytes, exceeds %d-byte limit", st.Size(), maxRuntimeLogBytes)
	}

	s := bufio.NewScanner(f)
	// Events are intentionally tiny. A generous 1 MiB ceiling prevents an
	// attacker-controlled log line from forcing Scanner to grow without bound.
	s.Buffer(make([]byte, 64<<10), maxRuntimeEventLine+1)
	var events []runtimeEvent
	lineNo := 0
	var consumed int64
	for s.Scan() {
		lineNo++
		line := s.Text()
		consumed += int64(len(line)) + 1
		if consumed > maxRuntimeLogBytes {
			return nil, fmt.Errorf("frida-import: runtime log exceeds %d-byte limit", maxRuntimeLogBytes)
		}
		idx := strings.Index(line, runtimeEventPrefix)
		if idx < 0 {
			continue
		}
		raw := strings.TrimSpace(line[idx+len(runtimeEventPrefix):])
		ev, err := jsonutil.DecodeStrictObject[runtimeEvent]([]byte(raw))
		if err != nil {
			return nil, fmt.Errorf("frida-import: event line %d: %w", lineNo, err)
		}
		if ev.SchemaVersion != MetadataSchemaVersion {
			return nil, fmt.Errorf("frida-import: event line %d schema %d, want %d", lineNo, ev.SchemaVersion, MetadataSchemaVersion)
		}
		if !strings.EqualFold(ev.GenerationID, binding.GenerationID) {
			return nil, fmt.Errorf("frida-import: event line %d generation id does not match exported hook generation", lineNo)
		}
		if !strings.EqualFold(ev.SourceSHA256, binding.SourceSHA256) {
			return nil, fmt.Errorf("frida-import: event line %d source sha256 does not match static provenance", lineNo)
		}
		if ev.SourceSize != binding.SourceSize {
			return nil, fmt.Errorf("frida-import: event line %d source size does not match static provenance", lineNo)
		}
		if ev.Architecture != binding.Architecture {
			return nil, fmt.Errorf("frida-import: event line %d architecture does not match static provenance", lineNo)
		}
		events = append(events, ev)
		if len(events) > maxRuntimeEvents {
			return nil, fmt.Errorf("frida-import: runtime event limit %d exceeded", maxRuntimeEvents)
		}
	}
	if err := s.Err(); err != nil {
		return nil, fmt.Errorf("frida-import: read runtime log: %w", err)
	}
	if len(events) == 0 {
		return nil, fmt.Errorf("frida-import: no %q records found in %s", strings.TrimSpace(runtimeEventPrefix), path)
	}
	return events, nil
}

func readStaticGeneration(dir string) (staticGeneration, error) {
	var out staticGeneration
	bindingBytes, present, err := readPinnedStaticFile(filepath.Join(dir, BindingFileName), 8<<20, true)
	if err != nil {
		return out, fmt.Errorf("frida-import: read %s: %w", BindingFileName, err)
	}
	if !present {
		return out, fmt.Errorf("frida-import: missing %s; run frida-export for this static generation first", BindingFileName)
	}
	binding, err := jsonutil.DecodeStrictObject[FridaBinding](bindingBytes)
	if err != nil {
		return out, fmt.Errorf("frida-import: decode %s: %w", BindingFileName, err)
	}
	if err := ValidateBinding(binding); err != nil {
		return out, fmt.Errorf("frida-import: %w", err)
	}
	if binding.AnalyzerVersion != cli.Version || binding.AnalyzerCommit != cli.Commit {
		return out, fmt.Errorf("frida-import: binding analyzer identity %s/%s does not match this aotopsy %s/%s", binding.AnalyzerVersion, binding.AnalyzerCommit, cli.Version, cli.Commit)
	}

	blobs := make(map[string][]byte, len(binding.Artifacts))
	for i, name := range GenerationArtifactNames() {
		expected := binding.Artifacts[i]
		b, gotPresent, err := readPinnedStaticFile(filepath.Join(dir, name), jsonutil.StandardLimits.MaxBytes, expected.Present)
		if err != nil {
			return out, fmt.Errorf("frida-import: read bound artifact %s: %w", name, err)
		}
		actual := DigestArtifact(name, b, gotPresent)
		if actual != expected {
			return out, fmt.Errorf("frida-import: static artifact %s does not match the Frida generation binding", name)
		}
		if gotPresent {
			blobs[name] = b
		}
	}

	prov, err := jsonutil.DecodeStrictObject[staticProvenance](blobs["provenance.json"])
	if err != nil {
		return out, fmt.Errorf("frida-import: decode provenance: %w", err)
	}
	if err := validateStaticProvenance(&prov); err != nil {
		return out, err
	}
	if !strings.EqualFold(prov.SHA256, binding.SourceSHA256) || prov.Size != binding.SourceSize || prov.SourceName != binding.ModuleName || prov.Arch != binding.Architecture || prov.DartVersion != binding.DartVersion {
		return out, fmt.Errorf("frida-import: provenance identity does not match Frida generation binding")
	}

	funcs, err := decodeStaticJSONLBytes[disasm.FuncRecord](blobs["functions.jsonl"])
	if err != nil {
		return out, fmt.Errorf("frida-import: decode functions.jsonl: %w", err)
	}
	if err := validateStaticFunctions(funcs); err != nil {
		return out, err
	}
	edges, err := decodeStaticJSONLBytes[disasm.CallEdgeRecord](blobs["call_edges.jsonl"])
	if err != nil {
		return out, fmt.Errorf("frida-import: decode call_edges.jsonl: %w", err)
	}
	if err := validateStaticCallEdges(edges); err != nil {
		return out, err
	}

	allFunctions := make([]FridaFunction, 0, len(funcs))
	for _, f := range funcs {
		allFunctions = append(allFunctions, FridaFunction{VA: f.PC, Name: f.Name, Owner: f.Owner, Size: f.Size})
	}
	allProbes := make([]FridaUnresolvedBLR, 0)
	for _, e := range edges {
		p, ok := RuntimeProbeForEdge(e)
		if !ok {
			continue
		}
		if p.Via == "dispatch_table" {
			p.ClassIDReg = DispatchClassIDRegister(binding.Architecture, binding.DartVersion)
		}
		allProbes = append(allProbes, p)
	}
	if !sameInstalledFunctions(binding.InstalledFunctions, installedFunctions(allFunctions)) {
		return out, fmt.Errorf("frida-import: installed function subset does not match bound functions.jsonl")
	}
	if !sameInstalledBLRs(binding.InstalledBLRs, installedBLRs(allProbes)) {
		return out, fmt.Errorf("frida-import: installed probe subset does not match bound call_edges.jsonl")
	}

	out.provenance = prov
	out.edges = edges
	out.functions = funcs
	out.binding = binding
	return out, nil
}

func readPinnedStaticFile(path string, limit int64, required bool) ([]byte, bool, error) {
	info, err := os.Lstat(path)
	if err != nil {
		if os.IsNotExist(err) && !required {
			return nil, false, nil
		}
		return nil, false, err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return nil, false, fmt.Errorf("%s is not a regular non-symlink file", path)
	}
	if info.Size() > limit {
		return nil, false, fmt.Errorf("%s is %d bytes, exceeds limit %d", path, info.Size(), limit)
	}
	f, err := os.Open(path)
	if err != nil {
		return nil, false, err
	}
	defer func() { _ = f.Close() }()
	opened, err := f.Stat()
	if err != nil {
		return nil, false, err
	}
	if !os.SameFile(info, opened) {
		return nil, false, fmt.Errorf("%s changed while being opened", path)
	}
	b, err := io.ReadAll(io.LimitReader(f, limit+1))
	if err != nil {
		return nil, false, err
	}
	if int64(len(b)) > limit {
		return nil, false, fmt.Errorf("%s exceeds byte limit %d", path, limit)
	}
	return b, true, nil
}

func decodeStaticJSONLBytes[T any](b []byte) ([]T, error) {
	limits := jsonutil.StandardLimits
	if int64(len(b)) > limits.MaxBytes {
		return nil, fmt.Errorf("input is %d bytes, exceeds limit %d", len(b), limits.MaxBytes)
	}
	s := bufio.NewScanner(bytes.NewReader(b))
	initial := 64 << 10
	if limits.MaxRecordBytes < initial {
		initial = limits.MaxRecordBytes
	}
	s.Buffer(make([]byte, initial), limits.MaxRecordBytes+1)
	var out []T
	lineNo := 0
	for s.Scan() {
		lineNo++
		line := append([]byte(nil), s.Bytes()...)
		if len(bytes.TrimSpace(line)) == 0 {
			return nil, fmt.Errorf("blank record at line %d", lineNo)
		}
		if len(out) >= limits.MaxRecords {
			return nil, fmt.Errorf("record limit %d exceeded at line %d", limits.MaxRecords, lineNo)
		}
		rec, err := jsonutil.DecodeStrictObject[T](line)
		if err != nil {
			return nil, fmt.Errorf("line %d: %w", lineNo, err)
		}
		out = append(out, rec)
	}
	if err := s.Err(); err != nil {
		return nil, fmt.Errorf("read line %d: %w", lineNo+1, err)
	}
	return out, nil
}

func readStaticCallEdges(path string) ([]disasm.CallEdgeRecord, error) {
	out, err := jsonutil.ReadJSONL[disasm.CallEdgeRecord](path, jsonutil.StandardLimits)
	if err != nil {
		return nil, fmt.Errorf("frida-import: read call_edges.jsonl: %w", err)
	}
	if err := validateStaticCallEdges(out); err != nil {
		return nil, err
	}
	return out, nil
}

func validateStaticCallEdges(out []disasm.CallEdgeRecord) error {
	for i, e := range out {
		if e.FromFunc == "" || e.FromPC == "" || e.Kind == "" {
			return fmt.Errorf("frida-import: call_edges line %d missing required field", i+1)
		}
	}
	return nil
}

func validateStaticFunctions(out []disasm.FuncRecord) error {
	for i, f := range out {
		if f.PC == "" || f.Name == "" || f.Size < 0 {
			return fmt.Errorf("frida-import: functions line %d missing/invalid required field", i+1)
		}
	}
	return nil
}

func readStaticProvenance(path string) (staticProvenance, error) {
	p, err := jsonutil.ReadJSONFile[staticProvenance](path, maxProvenanceBytes)
	if err != nil {
		return staticProvenance{}, fmt.Errorf("frida-import: read provenance: %w", err)
	}
	if err := validateStaticProvenance(&p); err != nil {
		return staticProvenance{}, err
	}
	return p, nil
}

func validateStaticProvenance(p *staticProvenance) error {
	if p == nil {
		return fmt.Errorf("frida-import: missing provenance")
	}
	if p.SourceName == "" || p.Size <= 0 || (p.Arch != "arm64" && p.Arch != "x64") || p.DartVersion == "" || len(p.SHA256) != 64 {
		return fmt.Errorf("frida-import: incomplete/invalid provenance identity")
	}
	if _, err := hex.DecodeString(p.SHA256); err != nil {
		return fmt.Errorf("frida-import: invalid provenance sha256: %w", err)
	}
	p.SHA256 = strings.ToLower(p.SHA256)
	return nil
}

func validateRuntimeTarget(ev runtimeEvent, prov staticProvenance, knownFunctions map[string]struct{}, knownFunctionPCs map[string]string) (string, error) {
	if ev.TargetVA == "" {
		return "", fmt.Errorf("missing target_va")
	}
	if ev.TargetModule == prov.SourceName {
		pc, err := canonicalRuntimeHex(ev.TargetVA)
		if err != nil {
			return "", fmt.Errorf("own-module target_va %q: %w", ev.TargetVA, err)
		}
		staticName, knownPC := knownFunctionPCs[pc]
		if ev.TargetName != "" {
			if _, ok := knownFunctions[ev.TargetName]; !ok {
				return "", fmt.Errorf("unknown own-module target name %q", ev.TargetName)
			}
			if !knownPC || staticName != ev.TargetName {
				return "", fmt.Errorf("target name %q does not match static function at %s", ev.TargetName, pc)
			}
			return ev.TargetName, nil
		}
		if knownPC {
			return staticName, nil
		}
		return pc, nil
	}

	if ev.TargetModule == "" {
		return "", fmt.Errorf("target has no owning module; absolute runtime addresses cannot be merged into module-relative static evidence")
	}

	if strings.ContainsAny(ev.TargetModule, "/\\\r\n\x00") {
		return "", fmt.Errorf("invalid external module name %q", ev.TargetModule)
	}
	if ev.TargetName != "" {
		return "", fmt.Errorf("external module %q supplied unsupported target_name %q", ev.TargetModule, ev.TargetName)
	}
	prefix := ev.TargetModule + "+"
	if !strings.HasPrefix(ev.TargetVA, prefix) {
		return "", fmt.Errorf("external target_va %q does not match module %q", ev.TargetVA, ev.TargetModule)
	}
	off, err := canonicalRuntimeHex(strings.TrimPrefix(ev.TargetVA, prefix))
	if err != nil {
		return "", fmt.Errorf("external target_va %q: %w", ev.TargetVA, err)
	}
	return ev.TargetModule + "+" + off, nil
}

func canonicalRuntimeHex(s string) (string, error) {
	if len(s) < 3 || !strings.HasPrefix(s, "0x") {
		return "", fmt.Errorf("expected 0x-prefixed hexadecimal value")
	}
	v, err := strconv.ParseUint(s[2:], 16, 64)
	if err != nil {
		return "", fmt.Errorf("invalid hexadecimal value: %w", err)
	}
	return fmt.Sprintf("0x%x", v), nil
}

func sortedTargetKeys(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedIntKeys(m map[int]struct{}) []int {
	out := make([]int, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Ints(out)
	return out
}

func totalRuntimeCalls(calls map[string]int) int {
	total := 0
	for _, n := range calls {
		total += n
	}
	return total
}
