package frida

import (
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

const maxSafeJSInteger = uint64(1<<53 - 1)

// GenerateFridaScript emits JavaScript from already-validated export metadata.
// The caller owns persistence of the JSON and script artifacts; keeping one
// in-memory value avoids a second file parse/TOCTOU window between export and
// script generation.
func GenerateFridaScript(meta FridaMetadata) (string, error) {
	// The script verifies immutable bytes from the loaded module, then installs
	// exactly the generation-bound hook/probe subset and emits tagged JSON lines
	// for frida-import. No runtime observation is accepted before identity passes.
	if err := ValidateMetadata(meta); err != nil {
		return "", err
	}

	var sb strings.Builder

	// Header
	sb.WriteString("'use strict';\n")
	sb.WriteString("// Auto-generated by aotopsy frida-export\n")
	sb.WriteString(fmt.Sprintf("// Arch: %s, Compressed: %v\n", meta.Architecture, meta.CompressedPointers))
	sb.WriteString(fmt.Sprintf("// Functions: %d, Call probes: %d, Dispatch: %d\n\n",
		len(meta.Functions), len(meta.CallProbes), len(meta.DispatchTable)))

	// Metadata embedded directly
	sb.WriteString("var META = {\n")
	sb.WriteString(fmt.Sprintf("  schemaVersion: %d,\n", meta.SchemaVersion))
	sb.WriteString(fmt.Sprintf("  generationID: %s,\n", jsString(meta.GenerationID)))
	sb.WriteString(fmt.Sprintf("  sourceSHA256: %s,\n", jsString(meta.SourceSHA256)))
	sb.WriteString(fmt.Sprintf("  sourceSize: %d,\n", meta.SourceSize))
	sb.WriteString(fmt.Sprintf("  moduleName: %s,\n", jsString(meta.ModuleName)))
	sb.WriteString(fmt.Sprintf("  arch: %s,\n", jsString(meta.Architecture)))
	sb.WriteString(fmt.Sprintf("  compressed: %v,\n", meta.CompressedPointers))
	sb.WriteString(fmt.Sprintf("  thrReg: %s,\n", jsString(meta.THRReg)))
	sb.WriteString(fmt.Sprintf("  ppReg: %s,\n", jsString(meta.PPReg)))
	sb.WriteString(fmt.Sprintf("  dtReg: %s,\n", jsString(meta.DTReg)))
	sb.WriteString(fmt.Sprintf("  heapBaseMode: %s,\n", jsString(meta.HeapBaseMode)))
	sb.WriteString(fmt.Sprintf("  heapBaseReg: %s,\n", jsString(meta.HeapBaseReg)))
	sb.WriteString(fmt.Sprintf("  heapBaseTHRField: %s,\n", jsString(meta.HeapBaseTHRField)))
	sb.WriteString(fmt.Sprintf("  headerBitOffset: %d,\n", meta.HeaderBitOffset))
	sb.WriteString(fmt.Sprintf("  headerBitWidth: %d,\n", meta.HeaderBitWidth))
	sb.WriteString(fmt.Sprintf("  pointerSize: %d\n", meta.PointerSize))
	sb.WriteString("};\n\n")

	sb.WriteString("var RUNTIME_IDENTITY_REGIONS = [\n")
	for i, region := range meta.RuntimeIdentity {
		if i > 0 {
			sb.WriteString(",\n")
		}
		sb.WriteString(fmt.Sprintf("  {kind: %s, offset: %s, size: %d, sha256: %s}",
			jsString(region.Kind), jsString(region.Offset), region.Size, jsString(region.SHA256)))
	}
	sb.WriteString("\n];\n\n")

	// Function name map (VA → name) for annotation. The hook set itself is
	// emitted separately below and is part of the generation binding.
	picked := scriptFunctionMap(meta.Functions)
	if len(meta.Functions) > maxFunctionMapEntries {
		sb.WriteString(fmt.Sprintf("// Function map (capped at %d named functions out of %d total)\n", len(picked), len(meta.Functions)))
	}
	sb.WriteString("var FUNC_MAP = {\n")
	for i, f := range picked {
		if i > 0 {
			sb.WriteString(",\n")
		}
		sb.WriteString(fmt.Sprintf("  %s: %s", jsString(f.VA), jsString(f.Name)))
	}
	sb.WriteString("\n};\n\n")

	sb.WriteString(fmt.Sprintf("// Exact installed function-hook set: %d\n", len(meta.InstalledFunctions)))
	sb.WriteString("var HOOK_SITES = [\n")
	for i, f := range meta.InstalledFunctions {
		if i > 0 {
			sb.WriteString(",\n")
		}
		sb.WriteString(fmt.Sprintf("  {addr: %s, name: %s}", jsString(f.VA), jsString(f.Name)))
	}
	sb.WriteString("\n];\n\n")

	// Dispatch table map (index → target name)
	// Cap at 2000 entries to keep script size manageable.
	maxDispatch := 2000
	if len(meta.DispatchTable) > maxDispatch {
		sb.WriteString(fmt.Sprintf("// Dispatch map (capped at %d entries out of %d total)\n", maxDispatch, len(meta.DispatchTable)))
		sb.WriteString("var DISPATCH_MAP = {\n")
		for i, d := range meta.DispatchTable[:maxDispatch] {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(fmt.Sprintf("  %d: %s", d.Index, jsString(d.Target)))
		}
	} else {
		sb.WriteString("var DISPATCH_MAP = {\n")
		for i, d := range meta.DispatchTable {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(fmt.Sprintf("  %d: %s", d.Index, jsString(d.Target)))
		}
	}
	sb.WriteString("\n};\n\n")

	// THR field map
	sb.WriteString("var THR_FIELDS = {\n")
	offsets := make([]int, 0, len(meta.THRFields))
	for off := range meta.THRFields {
		offsets = append(offsets, off)
	}
	sort.Ints(offsets)
	for _, off := range offsets {
		name := meta.THRFields[off]
		sb.WriteString(fmt.Sprintf("  0x%x: %s,\n", off, jsString(name)))
	}
	sb.WriteString("};\n\n")

	// Utility functions
	sb.WriteString(`// --- Utility functions ---
var RUNTIME_IDENTITY = null;
var identityFailure = false;

function getVerifiedModule() {
  var mod = Process.findModuleByName(META.moduleName);
  if (!mod) return null;
  if (Process.arch !== META.arch) {
    console.log('ERROR: runtime architecture ' + Process.arch + ' does not match metadata ' + META.arch);
    identityFailure = true;
    return null;
  }
  try {
    for (var i = 0; i < RUNTIME_IDENTITY_REGIONS.length; i++) {
      var region = RUNTIME_IDENTITY_REGIONS[i];
      var checksum = new Checksum('sha256');
      var remaining = region.size;
      var cursor = mod.base.add(parseInt(region.offset, 16));
      while (remaining > 0) {
        var take = Math.min(remaining, 1024 * 1024);
        var chunk = cursor.readByteArray(take);
        if (!chunk || chunk.byteLength !== take) {
          throw new Error('short runtime read for ' + region.kind);
        }
        checksum.update(chunk);
        cursor = cursor.add(take);
        remaining -= take;
      }
      var measuredRegionSHA256 = checksum.getString().toLowerCase();
      if (measuredRegionSHA256 !== region.sha256.toLowerCase()) {
        console.log('ERROR: loaded ' + META.moduleName + ' ' + region.kind + ' fingerprint does not match exported binary');
        identityFailure = true;
        return null;
      }
    }
    RUNTIME_IDENTITY = {
      sourceSHA256: META.sourceSHA256,
      sourceSize: META.sourceSize,
      architecture: Process.arch
    };
    return mod;
  } catch (e) {
    console.log('ERROR: cannot verify loaded ' + META.moduleName + ': ' + e);
    identityFailure = true;
    return null;
  }
}

function ptrToOffset(p, base) {
  return p.sub(base);
}

function offsetToName(offset) {
  var key = '0x' + offset.toString(16);
  return FUNC_MAP[key] || ('sub_' + offset.toString(16));
}

// extractClassId used to live here, reading a heap header out of what the
// dispatch probe called the "receiver register". Its only caller now takes
// the class id straight from DispatchTableNullErrorABI::kClassIdReg, which
// already holds it as an integer, so the header read is gone rather than
// left behind unused. META.headerBitOffset / headerBitWidth stay in the
// emitted metadata block -- they describe the object header layout and are
// part of the exported JSON that external scripts read -- but nothing in
// this generated script uses them any more.

function safeReadPtr(p) {
  try { return p.readPointer(); } catch(e) { return null; }
}

	function safeReadString(p, maxLen) {
  try {
    var s = p.readUtf8String(maxLen || 128);
    return s;
  } catch(e) { return null; }
	}

// Machine-readable runtime contract. Redirect Frida's stdout to a file and
// feed it directly to aotopsy frida-import --in <file>; ordinary console
// chatter is ignored by the importer.
function emitEvent(event) {
  if (!RUNTIME_IDENTITY) throw new Error('runtime identity was not verified');
  event.schema_version = META.schemaVersion;
  event.generation_id = META.generationID;
  event.source_sha256 = RUNTIME_IDENTITY.sourceSHA256;
  event.source_size = RUNTIME_IDENTITY.sourceSize;
  event.architecture = RUNTIME_IDENTITY.architecture;
  console.log('AOTOPSY_EVENT ' + JSON.stringify(event));
}

function resolveProbeTarget(site, ctx) {
  if (site.targetKind === 'register') {
    return ctx[site.reg] || null;
  }
  if (site.targetKind === 'x86_mem') {
    var basePtr = ctx[site.baseReg];
    if (!basePtr) return null;
    var ea = basePtr;
	    if (site.indexReg) {
	      var indexVal = ctx[site.indexReg];
	      if (!indexVal) return null;
	      var scaledIndex = indexVal;
	      if (site.scale === 2) scaledIndex = indexVal.shl(1);
	      else if (site.scale === 4) scaledIndex = indexVal.shl(2);
	      else if (site.scale === 8) scaledIndex = indexVal.shl(3);
	      ea = ea.add(scaledIndex);
	    }
	    if (site.disp > 0) ea = ea.add(site.disp);
	    else if (site.disp < 0) ea = ea.sub(-site.disp);
    return safeReadPtr(ea);
  }
  return null;
}

`)

	// Indirect-call probe addresses.
	sb.WriteString(fmt.Sprintf("// --- Exact installed call probe sites: %d ---\n", len(meta.InstalledCallProbes)))
	sb.WriteString("var CALL_SITES = [\n")
	for i, probe := range meta.InstalledCallProbes {
		if i > 0 {
			sb.WriteString(",\n")
		}
		sb.WriteString(fmt.Sprintf("  {addr: %s, func: %s, targetKind: %s, reg: %s, baseReg: %s, indexReg: %s, scale: %d, disp: %d, via: %s, classIdReg: %s}",
			jsString(probe.VA), jsString(probe.FromFunc), jsString(probe.TargetKind), jsString(probe.Reg), jsString(probe.BaseReg), jsString(probe.IndexReg), probe.Scale, probe.Disp, jsString(probe.Via), jsString(probe.ClassIDReg)))
	}
	sb.WriteString("\n];\n\n")

	// Main logic
	sb.WriteString(`// --- Anti-crash measures ---
// Problem: Frida agent crashes (SIGSEGV) in HeapTaskDaemon on devices
// with Houdini ARM-to-x86 translation (e.g. MuMu emulator).
// Solution: Exclude GC threads + Houdini/libflutter modules from interception.

var THREAD_NAMES = {};
var threadObserver = Process.attachThreadObserver({
  onAdded: function(thread) { THREAD_NAMES[thread.id] = thread.name || ''; },
  onRenamed: function(thread) { THREAD_NAMES[thread.id] = thread.name || ''; },
  onRemoved: function(thread) { delete THREAD_NAMES[thread.id]; }
});

function isGCThread() {
  var name = THREAD_NAMES[Process.getCurrentThreadId()] || '';
  return name.indexOf('HeapTask') >= 0 || name.indexOf('GC') >= 0 ||
         name.indexOf('Finalizer') >= 0 || name.indexOf('Worker') >= 0;
}

// Exclude Houdini and libflutter from Stalker to prevent crash
var houdiniMod = Process.findModuleByName('libhoudini.so');
if (houdiniMod) {
  console.log('[aotopsy] Houdini detected @ ' + houdiniMod.base + ' — excluding');
  try { Stalker.exclude({base: houdiniMod.base, size: houdiniMod.size}); } catch(e) {}
}
var flutterMod = Process.findModuleByName('libflutter.so');
if (flutterMod) {
  console.log('[aotopsy] libflutter.so @ ' + flutterMod.base + ' — excluding from Stalker');
  try { Stalker.exclude({base: flutterMod.base, size: flutterMod.size}); } catch(e) {}
}

// --- Main hooking logic ---
var base = null;
var hookCount = 0;
var probeCount = 0;

function installHooks() {
	  var verifiedModule = getVerifiedModule();
	  if (!verifiedModule) {
		  if (identityFailure) return;
		  console.log('[aotopsy] Waiting for ' + META.moduleName + '...');
    setTimeout(installHooks, 500);
    return;
  }
	  base = verifiedModule.base;
		  console.log('[aotopsy] ' + META.moduleName + ' base: ' + base);
	  console.log('[aotopsy] Installing ' + HOOK_SITES.length + ' function hooks...');

	  // Hook the exact generation-bound function subset.
	  var hooked = 0;
	  for (var i = 0; i < HOOK_SITES.length; i++) {
	    try {
	      var hook = HOOK_SITES[i];
	      var addr = base.add(parseInt(hook.addr, 16));
	      (function(h, a) {
	        Interceptor.attach(a, {
	          onEnter: function(args) {
            // Skip GC threads to prevent Frida agent crash
            if (isGCThread()) return;
	            this.fnName = h.name;
            this.args = [];
            for (var i = 0; i < 4; i++) {
              try { this.args.push(args[i].toString()); } catch(e) { this.args.push('?'); }
            }
		            emitEvent({type: 'function_enter', name: h.name, function_va: h.addr});
          },
          onLeave: function(retval) {
            if (this.fnName && hookCount++ < 500) {
              console.log('[aotopsy] <- ' + this.fnName + ' retval=' + retval);
            }
          }
        });
	      })(hook, addr);
      hooked++;
    } catch(e) {}
  }
  console.log('[aotopsy] Hooked ' + hooked + ' functions');

		  // Probe the exact generation-bound indirect-call subset.
		  var probed = 0;
		  for (var i = 0; i < CALL_SITES.length; i++) {
	    try {
	      var site = CALL_SITES[i];
      var addr = base.add(parseInt(site.addr, 16));
      (function(s, a) {
        Interceptor.attach(a, {
          onEnter: function(args) {
            if (isGCThread()) return; // skip GC threads
            var targetPtr = resolveProbeTarget(s, this.context);
            if (!targetPtr) return;
		            var classId = -1;
		            // classIdReg is versioned at export time. ARM64 before Dart
		            // 2.13 mutates the CID register while forming the dispatch-table
		            // index, so those probes intentionally carry no classIdReg.
		            if (s.classIdReg) {
		              var cidVal = this.context[s.classIdReg];
		              if (cidVal) classId = cidVal.toInt32();
		            }

	            var targetModule = Process.findModuleByAddress(targetPtr);
	            if (!targetModule) {
	              console.log('[aotopsy] target has no owning module; skipping runtime resolution at ' + s.addr + ': ' + targetPtr);
	              return;
	            }
	            var targetVA = targetPtr.toString();
	            var targetName = '';
	            var targetModuleName = targetModule.name;
	            var moduleOffset = targetPtr.sub(targetModule.base);
			            if (targetModule.base.equals(base)) {
	              targetVA = '0x' + moduleOffset.toString(16);
	              var key = targetVA;
	              targetName = FUNC_MAP[key] || '';
	            } else {
	              targetVA = targetModule.name + '+0x' + moduleOffset.toString(16);
	            }

		            emitEvent({
		              type: 'dispatch',
			              call_addr: s.addr,
	              from_func: s.func,
	              target_va: targetVA,
              target_name: targetName,
              target_module: targetModuleName,
              class_id: classId
            });
          }
        });
      })(site, addr);
      probed++;
    } catch(e) {}
  }
	  console.log('[aotopsy] Probed ' + probed + ' indirect call sites');
  console.log('[aotopsy] Ready. Interact with the app to capture data.');
}

// Start
installHooks();
`)

	return sb.String(), nil
}

// ValidateMetadata enforces the semantic contract of frida_metadata.json.
// Persistence-only callers must invoke this too; generating JavaScript is not
// the validator side effect.
func ValidateMetadata(meta FridaMetadata) error {
	if meta.SchemaVersion != MetadataSchemaVersion {
		return fmt.Errorf("frida script: unsupported metadata schema %d", meta.SchemaVersion)
	}
	if strings.TrimSpace(meta.AnalyzerVersion) == "" || strings.TrimSpace(meta.AnalyzerCommit) == "" {
		return fmt.Errorf("frida script: missing analyzer identity")
	}
	if len(meta.SourceSHA256) != 64 {
		return fmt.Errorf("frida script: invalid source sha256")
	}
	if _, err := hex.DecodeString(meta.SourceSHA256); err != nil {
		return fmt.Errorf("frida script: invalid source sha256: %w", err)
	}
	if meta.SourceSize <= 0 {
		return fmt.Errorf("frida script: invalid source size %d", meta.SourceSize)
	}
	if uint64(meta.SourceSize) > maxSafeJSInteger {
		return fmt.Errorf("frida script: source size %d exceeds exact JavaScript integer range", meta.SourceSize)
	}
	if strings.TrimSpace(meta.ModuleName) == "" || strings.ContainsAny(meta.ModuleName, `/\\`) {
		return fmt.Errorf("frida script: invalid module name %q", meta.ModuleName)
	}
	if strings.TrimSpace(meta.DartVersion) == "" {
		return fmt.Errorf("frida script: missing Dart version")
	}
	if meta.Architecture != "arm64" && meta.Architecture != "x64" {
		return fmt.Errorf("frida script: unsupported architecture %q", meta.Architecture)
	}
	if meta.PointerSize != 4 && meta.PointerSize != 8 {
		return fmt.Errorf("frida script: invalid pointer size %d", meta.PointerSize)
	}
	wantPointerSize := 8
	if meta.CompressedPointers {
		wantPointerSize = 4
	}
	if meta.PointerSize != wantPointerSize {
		return fmt.Errorf("frida script: pointer size %d does not match compressed-pointers=%v", meta.PointerSize, meta.CompressedPointers)
	}
	for label, reg := range map[string]string{"thr": meta.THRReg, "pp": meta.PPReg, "dispatch": meta.DTReg} {
		if !isContextRegisterForArch(meta.Architecture, reg) {
			return fmt.Errorf("frida script: invalid %s register %q", label, reg)
		}
	}
	switch meta.HeapBaseMode {
	case "none":
	case "register", "heap_bits":
		if !isContextRegisterForArch(meta.Architecture, meta.HeapBaseReg) {
			return fmt.Errorf("frida script: invalid heap-base register %q", meta.HeapBaseReg)
		}
	case "thread_field":
		if strings.TrimSpace(meta.HeapBaseTHRField) == "" {
			return fmt.Errorf("frida script: thread-field heap base has no field name")
		}
	default:
		return fmt.Errorf("frida script: invalid heap-base mode %q", meta.HeapBaseMode)
	}
	if meta.HeaderBitOffset < 0 || meta.HeaderBitOffset > 63 || meta.HeaderBitWidth <= 0 || meta.HeaderBitWidth > 64-meta.HeaderBitOffset {
		return fmt.Errorf("frida script: invalid class-id bit layout offset=%d width=%d", meta.HeaderBitOffset, meta.HeaderBitWidth)
	}
	for i, f := range meta.Functions {
		if strings.TrimSpace(f.Name) == "" || f.Size < 0 {
			return fmt.Errorf("frida script: function %d has invalid name/size", i)
		}
		if err := validateJSOffset(f.VA); err != nil {
			return fmt.Errorf("frida script: function %d: %w", i, err)
		}
	}
	for i, p := range meta.CallProbes {
		if err := validateJSOffset(p.VA); err != nil {
			return fmt.Errorf("frida script: probe %d: %w", i, err)
		}
		switch p.TargetKind {
		case "register":
			if !isContextRegisterForArch(meta.Architecture, p.Reg) {
				return fmt.Errorf("frida script: probe %d invalid register %q", i, p.Reg)
			}
		case "x86_mem":
			if meta.Architecture != "x64" || !isContextRegisterForArch(meta.Architecture, p.BaseReg) {
				return fmt.Errorf("frida script: probe %d invalid x86 memory base %q", i, p.BaseReg)
			}
			if p.IndexReg != "" && !isContextRegisterForArch(meta.Architecture, p.IndexReg) {
				return fmt.Errorf("frida script: probe %d invalid x86 memory index %q", i, p.IndexReg)
			}
			if p.IndexReg == "" && p.Scale != 0 {
				return fmt.Errorf("frida script: probe %d has x86 scale %d without an index register", i, p.Scale)
			}
			if p.IndexReg != "" && p.Scale != 1 && p.Scale != 2 && p.Scale != 4 && p.Scale != 8 {
				return fmt.Errorf("frida script: probe %d invalid x86 scale %d", i, p.Scale)
			}
			if p.Disp < minX86MemoryDisp || p.Disp > maxX86MemoryDisp {
				return fmt.Errorf("frida script: probe %d x86 displacement %d does not fit disp32", i, p.Disp)
			}
		default:
			return fmt.Errorf("frida script: probe %d invalid target kind %q", i, p.TargetKind)
		}
		if p.ClassIDReg != "" {
			if p.Via != "dispatch_table" || !isContextRegisterForArch(meta.Architecture, p.ClassIDReg) {
				return fmt.Errorf("frida script: probe %d invalid class-id register %q", i, p.ClassIDReg)
			}
		}
	}
	for i, d := range meta.DispatchTable {
		if d.Index < 0 || strings.TrimSpace(d.Target) == "" {
			return fmt.Errorf("frida script: dispatch entry %d invalid", i)
		}
	}
	for off := range meta.THRFields {
		if off < 0 {
			return fmt.Errorf("frida script: negative THR field offset %d", off)
		}
	}
	if !sameInstalledFunctions(meta.InstalledFunctions, installedFunctions(meta.Functions)) {
		return fmt.Errorf("frida script: installed function subset does not match stock hook plan")
	}
	if !sameInstalledCallProbes(meta.InstalledCallProbes, installedCallProbes(meta.CallProbes)) {
		return fmt.Errorf("frida script: installed call-probe subset does not match stock probe plan")
	}
	if err := ValidateBinding(BindingFromMetadata(meta)); err != nil {
		return fmt.Errorf("frida script: %w", err)
	}
	return nil
}

func validateJSOffset(s string) error {
	if len(s) < 3 || !strings.HasPrefix(s, "0x") {
		return fmt.Errorf("invalid module offset %q", s)
	}
	v, err := strconv.ParseUint(s[2:], 16, 64)
	if err != nil {
		return fmt.Errorf("invalid module offset %q", s)
	}
	if v > maxSafeJSInteger {
		return fmt.Errorf("module offset %q exceeds exact JavaScript integer range", s)
	}
	return nil
}

func jsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}
