package frida

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

func GenerateFridaScriptFromMeta(metaPath string) string {
	// from frida_metadata.json. The script:
	// 1. Loads metadata
	// 2. Hooks all named functions (entry/exit logging)
	// 3. Probes all unresolved BLR sites (reads target register at runtime)
	// 4. Extracts class IDs from object headers at BLR sites
	// 5. Sends results back via send() for frida-import to consume
	// Read metadata
	data, err := os.ReadFile(metaPath)
	if err != nil {
		return fmt.Sprintf("// ERROR: cannot read %s: %v\n", metaPath, err)
	}
	var meta FridaMetadata
	if err := json.Unmarshal(data, &meta); err != nil {
		return fmt.Sprintf("// ERROR: cannot parse %s: %v\n", metaPath, err)
	}

	var sb strings.Builder

	// Header
	sb.WriteString("'use strict';\n")
	sb.WriteString("// Auto-generated by aotopsy frida-export\n")
	sb.WriteString(fmt.Sprintf("// Dart: %s, Arch: %s, Compressed: %v\n",
		meta.DartVersion, meta.Architecture, meta.CompressedPointers))
	sb.WriteString(fmt.Sprintf("// Functions: %d, Unresolved BLRs: %d, Dispatch: %d\n\n",
		len(meta.Functions), len(meta.UnresolvedBLRs), len(meta.DispatchTable)))

	// Metadata embedded directly
	sb.WriteString("var META = {\n")
	sb.WriteString(fmt.Sprintf("  arch: '%s',\n", meta.Architecture))
	sb.WriteString(fmt.Sprintf("  compressed: %v,\n", meta.CompressedPointers))
	sb.WriteString(fmt.Sprintf("  thrReg: '%s',\n", meta.THRReg))
	sb.WriteString(fmt.Sprintf("  ppReg: '%s',\n", meta.PPReg))
	sb.WriteString(fmt.Sprintf("  dtReg: '%s',\n", meta.DTReg))
	sb.WriteString(fmt.Sprintf("  heapBaseReg: '%s',\n", meta.HeapBaseReg))
	sb.WriteString(fmt.Sprintf("  headerBitOffset: %d,\n", meta.HeaderBitOffset))
	sb.WriteString(fmt.Sprintf("  headerBitWidth: %d,\n", meta.HeaderBitWidth))
	sb.WriteString(fmt.Sprintf("  pointerSize: %d\n", meta.PointerSize))
	sb.WriteString("};\n\n")

	// Function name map (VA → name) for annotation
	// Cap at 500 functions to keep script size manageable.
	// For full function map, use the JSON metadata file directly.
	// Skip both sub_ and stub_ (unnamed/synthesized functions).
	maxFuncs := 500
	if len(meta.Functions) > maxFuncs {
		var picked []FridaFunction
		for _, f := range meta.Functions {
			if !strings.HasPrefix(f.Name, "sub_") && !strings.HasPrefix(f.Name, "stub_") {
				picked = append(picked, f)
				if len(picked) >= maxFuncs {
					break
				}
			}
		}
		sb.WriteString(fmt.Sprintf("// Function map (capped at %d named functions out of %d total)\n", len(picked), len(meta.Functions)))
		sb.WriteString("var FUNC_MAP = {\n")
		for i, f := range picked {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(fmt.Sprintf("  '%s': '%s'", f.VA, escapeJS(f.Name)))
		}
	} else {
		sb.WriteString("var FUNC_MAP = {\n")
		for i, f := range meta.Functions {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(fmt.Sprintf("  '%s': '%s'", f.VA, escapeJS(f.Name)))
		}
	}
	sb.WriteString("\n};\n\n")

	// Dispatch table map (index → target name)
	// Cap at 2000 entries to keep script size manageable.
	maxDispatch := 2000
	if len(meta.DispatchTable) > maxDispatch {
		sb.WriteString(fmt.Sprintf("// Dispatch map (capped at %d entries out of %d total)\n", maxDispatch, len(meta.DispatchTable)))
		sb.WriteString("var DISPATCH_MAP = {\n")
		for i, d := range meta.DispatchTable[:maxDispatch] {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(fmt.Sprintf("  %d: '%s'", d.Index, escapeJS(d.Target)))
		}
	} else {
		sb.WriteString("var DISPATCH_MAP = {\n")
		for i, d := range meta.DispatchTable {
			if i > 0 {
				sb.WriteString(",\n")
			}
			sb.WriteString(fmt.Sprintf("  %d: '%s'", d.Index, escapeJS(d.Target)))
		}
	}
	sb.WriteString("\n};\n\n")

	// THR field map
	sb.WriteString("var THR_FIELDS = {\n")
	for off, name := range meta.THRFields {
		sb.WriteString(fmt.Sprintf("  0x%x: '%s',\n", off, escapeJS(name)))
	}
	sb.WriteString("};\n\n")

	// Utility functions
	sb.WriteString(`// --- Utility functions ---
function getModuleBase() {
  var mod = Process.findModuleByName('libapp.so');
  if (!mod) { console.log('ERROR: libapp.so not found'); return null; }
  return mod.base;
}

function ptrToOffset(p, base) {
  return p.sub(base);
}

function offsetToName(offset) {
  var key = '0x' + offset.toString(16);
  return FUNC_MAP[key] || ('sub_' + offset.toString(16));
}

// extractClassId used to live here, reading a heap header out of what the
// dispatch probe called the "receiver register". Its only caller now takes
// the class id straight from DispatchTableNullErrorABI::kClassIdReg, which
// already holds it as an integer, so the header read is gone rather than
// left behind unused. META.headerBitOffset / headerBitWidth stay in the
// emitted metadata block -- they describe the object header layout and are
// part of the exported JSON that external scripts read -- but nothing in
// this generated script uses them any more.

function safeReadPtr(p) {
  try { return p.readPointer(); } catch(e) { return null; }
}

function safeReadString(p, maxLen) {
  try {
    var s = p.readUtf8String(maxLen || 128);
    return s;
  } catch(e) { return null; }
}

`)

	// BLR probe addresses
	sb.WriteString(fmt.Sprintf("// --- Unresolved BLR probe sites: %d ---\n", len(meta.UnresolvedBLRs)))
	sb.WriteString("var BLR_SITES = [\n")
	for i, blr := range meta.UnresolvedBLRs {
		if i > 0 {
			sb.WriteString(",\n")
		}
		sb.WriteString(fmt.Sprintf("  {addr: '%s', func: '%s', reg: '%s', via: '%s'}",
			blr.VA, escapeJS(blr.FromFunc), blr.Reg, blr.Via))
	}
	sb.WriteString("\n];\n\n")

	// Main logic
	sb.WriteString(`// --- Anti-crash measures ---
// Problem: Frida agent crashes (SIGSEGV) in HeapTaskDaemon on devices
// with Houdini ARM-to-x86 translation (e.g. MuMu emulator).
// Solution: Exclude GC threads + Houdini/libflutter modules from interception.

function isGCThread() {
  try {
    var name = Thread.currentName ? Thread.currentName() : '';
    return name.indexOf('HeapTask') >= 0 || name.indexOf('GC') >= 0 ||
           name.indexOf('Finalizer') >= 0 || name.indexOf('Worker') >= 0;
  } catch(e) { return false; }
}

// Exclude Houdini and libflutter from Stalker to prevent crash
var houdiniMod = Process.findModuleByName('libhoudini.so');
if (houdiniMod) {
  console.log('[aotopsy] Houdini detected @ ' + houdiniMod.base + ' — excluding');
  try { Stalker.exclude({base: houdiniMod.base, size: houdiniMod.size}); } catch(e) {}
}
var flutterMod = Process.findModuleByName('libflutter.so');
if (flutterMod) {
  console.log('[aotopsy] libflutter.so @ ' + flutterMod.base + ' — excluding from Stalker');
  try { Stalker.exclude({base: flutterMod.base, size: flutterMod.size}); } catch(e) {}
}

// --- Main hooking logic ---
var base = null;
var hookCount = 0;
var probeCount = 0;
var MAX_HOOKS = 50;   // conservative to avoid Frida agent crash
var MAX_PROBES = 100; // conservative for BLR probes

function installHooks() {
  base = getModuleBase();
  if (!base) {
    console.log('[aotopsy] Waiting for libapp.so...');
    setTimeout(installHooks, 500);
    return;
  }
  console.log('[aotopsy] libapp.so base: ' + base);
  console.log('[aotopsy] Installing ' + Math.min(MAX_HOOKS, FUNC_MAP_COUNT) + ' function hooks...');

  // Hook named functions (capped)
  var hooked = 0;
  for (var va in FUNC_MAP) {
    if (hooked >= MAX_HOOKS) break;
    try {
      var addr = base.add(parseInt(va, 16));
      var name = FUNC_MAP[va];
      (function(n, a) {
        Interceptor.attach(a, {
          onEnter: function(args) {
            // Skip GC threads to prevent Frida agent crash
            if (isGCThread()) return;
            this.fnName = n;
            this.args = [];
            for (var i = 0; i < 4; i++) {
              try { this.args.push(args[i].toString()); } catch(e) { this.args.push('?'); }
            }
          },
          onLeave: function(retval) {
            if (this.fnName && hookCount++ < 500) {
              send({type: 'function', name: this.fnName, args: this.args, ret: retval.toString()});
            }
          }
        });
      })(name, addr);
      hooked++;
    } catch(e) {}
  }
  console.log('[aotopsy] Hooked ' + hooked + ' functions');

  // Probe unresolved BLR sites (capped)
  var probed = 0;
  for (var i = 0; i < BLR_SITES.length && probed < MAX_PROBES; i++) {
    try {
      var site = BLR_SITES[i];
      var addr = base.add(parseInt(site.addr, 16));
      (function(s, a) {
        Interceptor.attach(a, {
          onEnter: function(args) {
            if (isGCThread()) return; // skip GC threads
            var reg = s.reg.toLowerCase();
            var targetPtr = this.context[reg];
            if (!targetPtr) return;

            var offset = targetPtr.sub(base);
            // DispatchTableNullErrorABI::kClassIdReg holds the receiver's
            // class id as a plain integer -- x0 on ARM64, rcx on x86_64 --
            // because EmitDispatchTableCall uses it as the table index:
            //   arm64   add LR, cid_reg, #off ; call [DT_REG + LR*8]
            //   x86_64  call [table_reg + cid_reg*8 + off]
            // This used to read x1 / rcx as a receiver POINTER and pull a
            // heap header out of it, which on x86_64 meant dereferencing
            // the class id itself: an address equal to a small integer,
            // so every probe faulted and reported -1.
            var cidReg = (META.arch === 'arm64') ? 'x0' : 'rcx';
            var classId = -1;
            var cidVal = this.context[cidReg];
            if (cidVal) {
              classId = cidVal.toInt32();
            }

            var targetName = offsetToName(offset);

            send({
              type: 'dispatch',
              blr_addr: s.addr,
              from_func: s.func,
              reg: s.reg,
              via: s.via,
              target_va: '0x' + offset.toString(16),
              target_name: targetName,
              class_id: classId
            });
          }
        });
      })(site, addr);
      probed++;
    } catch(e) {}
  }
  console.log('[aotopsy] Probed ' + probed + ' BLR sites');
  console.log('[aotopsy] Ready. Interact with the app to capture data.');
}

// Count functions for logging
var FUNC_MAP_COUNT = 0;
for (var k in FUNC_MAP) FUNC_MAP_COUNT++;

// Start
installHooks();
`)

	return sb.String()
}
func escapeJS(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	return s
}
